/**
 * Server-action error i18n (W4, owner ruling 1).
 *
 * Server actions return stable error CODES over the wire — the string
 * `"@err:" + code` — and the CLIENT maps them through `t()` at render
 * time (`resolveActionError`), so the operator sees the message in their
 * own locale. Plain (non-sentinel) strings pass through untouched: that is
 * the back-compat path for unmigrated actions and for genuinely dynamic
 * messages (Supabase `error.message` passthroughs, interpolated strings).
 *
 * Adding a code: add the English string to ACTION_ERROR_FALLBACKS below,
 * mirror it under `errors.*` in src/messages/en.json (then resync es/pt),
 * and return `actionError("your.code", "English text")` from the action.
 * The catalog is guarded by src/lib/errors-canon.test.ts.
 *
 * This module is isomorphic (no server-only imports): actions build the
 * sentinel on the server, FormShell + bespoke render sites resolve it on
 * the client.
 */

export const ACTION_ERROR_PREFIX = "@err:";

/**
 * English fallback for every action error code. Also the SSOT the
 * `errors.*` namespace in src/messages/en.json is generated from — the two
 * are kept identical by errors-canon.test.ts.
 */
export const ACTION_ERROR_FALLBACKS = {
 "a-catalog-item-is-no-longer-available": "A Catalog Item Is No Longer Available",
 "a-code-with-that-name-already-exists": "A code with that name already exists.",
 "a-daily-log-already-exists-for-this-project-on": "A daily log already exists for this project on that date. Open it to edit.",
 "a-line-s-end-date-precedes-its-start-date": "A Line's End Date Precedes Its Start Date",
 "a-pending-invite-already-exists-for-this-email": "A pending invite already exists for this email.",
 "a-person-can-t-report-to-themselves": "A person can't report to themselves.",
 "a-promoter-with-that-ref-code-already-exists": "A promoter with that ref code already exists.",
 "a-role-with-that-name-already-exists": "A role with that name already exists",
 "a-team-with-that-slug-already-exists-in-this": "A team with that slug already exists in this org.",
 "add-at-least-one-contact-one-per-line-name": "Add at least one contact, one per line: Name <email> or a bare email",
 "add-your-name-and-a-signature-first": "Add your name and a signature first.",
 "an-entity-can-t-consolidate-into-itself": "An entity can't consolidate into itself",
 "article-has-no-text-to-embed": "Article has no text to embed.",
 "assignee-is-not-in-your-organization": "Assignee is not in your organization",
 "atom-belongs-to-a-different-project": "Atom belongs to a different project",
 "auth.admin.change-capabilities": "You need admin access to change capabilities",
 "auth.admin.change-enforcement": "You need admin access to change enforcement",
 "auth.capability.people-manage": "You need the people:manage capability to assign people to a project.",
 "auth.capability.people-manage-2": "You need the people:manage capability to edit reporting lines.",
 "auth.manager-plus.add-key-results": "Only manager+ can add key results",
 "auth.manager-plus.add-stories": "Only manager+ can add stories",
 "auth.manager-plus.add-ticket-types": "Only manager+ can add ticket types",
 "auth.manager-plus.assign-catalog-items": "Only manager+ can assign catalog items",
 "auth.manager-plus.author-advance-packets": "Only manager+ can author advance packets",
 "auth.manager-plus.author-courses": "Only manager+ can author courses",
 "auth.manager-plus.author-onboarding-flows": "Only manager+ can author onboarding flows",
 "auth.manager-plus.award-rfqs": "Only manager+ can award RFQs",
 "auth.manager-plus.bind-scan-codes": "Only manager+ can bind scan codes",
 "auth.manager-plus.book-submissions": "Only manager+ can book submissions",
 "auth.manager-plus.broadcast-work-orders": "Only manager+ can broadcast work orders",
 "auth.manager-plus.change-beo-status": "Only manager+ can change BEO status",
 "auth.manager-plus.change-envelope-state": "Only manager+ can change envelope state",
 "auth.manager-plus.change-invoice-status": "Only manager+ can change invoice status",
 "auth.manager-plus.change-po-status": "Only manager+ can change PO status",
 "auth.manager-plus.change-project-state": "Only manager+ can change project state",
 "auth.manager-plus.change-proposal-status": "Only manager+ can change proposal status",
 "auth.manager-plus.change-sheet-state": "Only manager+ can change sheet state",
 "auth.manager-plus.close-job-postings": "Only manager+ can close job postings",
 "auth.manager-plus.convert-estimates": "Only manager+ can convert estimates",
 "auth.manager-plus.convert-proposals": "Only manager+ can convert proposals",
 "auth.manager-plus.convert-requisitions": "Only manager+ can convert requisitions",
 "auth.manager-plus.create-approval-delegations": "Only manager+ can create approval delegations",
 "auth.manager-plus.create-approval-policies": "Only manager+ can create approval policies",
 "auth.manager-plus.create-assets": "Only manager+ can create assets",
 "auth.manager-plus.create-beos": "Only manager+ can create BEOs",
 "auth.manager-plus.create-bookings": "Only manager+ can create bookings",
 "auth.manager-plus.create-budgets": "Only manager+ can create budgets",
 "auth.manager-plus.create-channels": "Only manager+ can create channels",
 "auth.manager-plus.create-clients": "Only manager+ can create clients",
 "auth.manager-plus.create-contracts": "Only manager+ can create contracts",
 "auth.manager-plus.create-corrective-tasks": "Only manager+ can create corrective tasks",
 "auth.manager-plus.create-day-sheets": "Only manager+ can create day sheets",
 "auth.manager-plus.create-discount-codes": "Only manager+ can create discount codes",
 "auth.manager-plus.create-documents": "Only manager+ can create documents",
 "auth.manager-plus.create-draws": "Only manager+ can create draws",
 "auth.manager-plus.create-envelopes": "Only manager+ can create envelopes",
 "auth.manager-plus.create-event-types": "Only manager+ can create event types",
 "auth.manager-plus.create-events": "Only manager+ can create events",
 "auth.manager-plus.create-goals": "Only manager+ can create goals",
 "auth.manager-plus.create-guest-lists": "Only manager+ can create guest lists",
 "auth.manager-plus.create-invoices": "Only manager+ can create invoices",
 "auth.manager-plus.create-job-postings": "Only manager+ can create job postings",
 "auth.manager-plus.create-payment-applications": "Only manager+ can create payment applications",
 "auth.manager-plus.create-po-change-orders": "Only manager+ can create PO change orders",
 "auth.manager-plus.create-projects": "Only manager+ can create projects",
 "auth.manager-plus.create-promoters": "Only manager+ can create promoters",
 "auth.manager-plus.create-proposals": "Only manager+ can create proposals",
 "auth.manager-plus.create-purchase-orders": "Only manager+ can create purchase orders",
 "auth.manager-plus.create-reservations": "Only manager+ can create reservations",
 "auth.manager-plus.create-rfqs": "Only manager+ can create RFQs",
 "auth.manager-plus.create-sheets": "Only manager+ can create sheets",
 "auth.manager-plus.create-spaces": "Only manager+ can create spaces",
 "auth.manager-plus.create-sprints": "Only manager+ can create sprints",
 "auth.manager-plus.create-tables": "Only manager+ can create tables",
 "auth.manager-plus.create-talent-profiles": "Only manager+ can create talent profiles",
 "auth.manager-plus.create-tiered-holds": "Only manager+ can create tiered holds",
 "auth.manager-plus.create-tours": "Only manager+ can create tours",
 "auth.manager-plus.create-vendors": "Only manager+ can create vendors",
 "auth.manager-plus.create-warranties": "Only manager+ can create warranties",
 "auth.manager-plus.create-whiteboards": "Only manager+ can create whiteboards",
 "auth.manager-plus.create-wip-snapshots": "Only manager+ can create WIP snapshots",
 "auth.manager-plus.decide-applications": "Only manager+ can decide applications",
 "auth.manager-plus.decide-submission-outcomes": "Only manager+ can decide submission outcomes",
 "auth.manager-plus.define-badges": "Only manager+ can define badges",
 "auth.manager-plus.delete-sheets": "Only manager+ can delete sheets",
 "auth.manager-plus.edit-advancing-presets": "Only manager+ can edit advancing presets",
 "auth.manager-plus.edit-announcements": "Only manager+ can edit announcements",
 "auth.manager-plus.edit-approval-policies": "Only manager+ can edit approval policies",
 "auth.manager-plus.edit-beos": "Only manager+ can edit BEOs",
 "auth.manager-plus.edit-bookings": "Only manager+ can edit bookings",
 "auth.manager-plus.edit-client-branding": "Only manager+ can edit client branding",
 "auth.manager-plus.edit-co-pro-partnerships": "Only manager+ can edit co-pro partnerships",
 "auth.manager-plus.edit-contracts": "Only manager+ can edit contracts",
 "auth.manager-plus.edit-credentials": "Only manager+ can edit credentials",
 "auth.manager-plus.edit-depreciation": "Only manager+ can edit depreciation",
 "auth.manager-plus.edit-documents": "Only manager+ can edit documents",
 "auth.manager-plus.edit-goals": "Only manager+ can edit goals",
 "auth.manager-plus.edit-guest-lists": "Only manager+ can edit guest lists",
 "auth.manager-plus.edit-invoices": "Only manager+ can edit invoices",
 "auth.manager-plus.edit-job-postings": "Only manager+ can edit job postings",
 "auth.manager-plus.edit-journal-entries": "Only manager+ can edit journal entries",
 "auth.manager-plus.edit-offer-letters": "Only manager+ can edit offer letters",
 "auth.manager-plus.edit-open-calls": "Only manager+ can edit open calls",
 "auth.manager-plus.edit-settlement-records": "Only manager+ can edit settlement records",
 "auth.manager-plus.edit-sheets": "Only manager+ can edit sheets",
 "auth.manager-plus.edit-talent-profiles": "Only manager+ can edit talent profiles",
 "auth.manager-plus.edit-the-chart-of-accounts": "Only manager+ can edit the chart of accounts",
 "auth.manager-plus.edit-whiteboards": "Only manager+ can edit whiteboards",
 "auth.manager-plus.finalize-settlements": "Only manager+ can finalize settlements",
 "auth.manager-plus.import-budgets": "Only manager+ can import budgets",
 "auth.manager-plus.log-maintenance": "Only manager+ can log maintenance",
 "auth.manager-plus.manage-templates": "Only manager+ can manage templates",
 "auth.manager-plus.manage-time-clock-zones": "Only manager+ can manage time-clock zones",
 "auth.manager-plus.operate-advance-sends": "Only manager+ can operate advance sends",
 "auth.manager-plus.pair-account-managers": "Only manager+ can pair account managers",
 "auth.manager-plus.post-change-orders-to-budget": "Only manager+ can post change orders to budget",
 "auth.manager-plus.post-journal-entries": "Only manager+ can post journal entries",
 "auth.manager-plus.post-open-calls": "Only manager+ can post open calls",
 "auth.manager-plus.prepare-advance-sends": "Only manager+ can prepare advance sends",
 "auth.manager-plus.publish-announcements": "Only manager+ can publish announcements",
 "auth.manager-plus.publish-day-sheets": "Only manager+ can publish day sheets",
 "auth.manager-plus.publish-job-postings": "Only manager+ can publish job postings",
 "auth.manager-plus.publish-polls": "Only manager+ can publish polls",
 "auth.manager-plus.publish-rfqs": "Only manager+ can publish RFQs",
 "auth.manager-plus.publish-surveys": "Only manager+ can publish surveys",
 "auth.manager-plus.publish-talent-profiles": "Only manager+ can publish talent profiles",
 "auth.manager-plus.record-a-3-way-match": "Only manager+ can record a 3-way match",
 "auth.manager-plus.record-approval-decisions": "Only manager+ can record approval decisions",
 "auth.manager-plus.record-attributions": "Only manager+ can record attributions",
 "auth.manager-plus.record-credentials": "Only manager+ can record credentials",
 "auth.manager-plus.record-goods-receipts": "Only manager+ can record goods receipts",
 "auth.manager-plus.record-received-lines": "Only manager+ can record received lines",
 "auth.manager-plus.record-sales-snapshots": "Only manager+ can record sales snapshots",
 "auth.manager-plus.reject-documents": "Only manager+ can reject documents",
 "auth.manager-plus.release-tiered-holds": "Only manager+ can release tiered holds",
 "auth.manager-plus.rotate-letter-access-codes": "Only manager+ can rotate letter access codes",
 "auth.manager-plus.route-change-orders-to-approvals": "Only manager+ can route change orders to approvals",
 "auth.manager-plus.route-purchase-orders-to-approvals": "Only manager+ can route purchase orders to approvals",
 "auth.manager-plus.schedule-live-sessions": "Only manager+ can schedule live sessions",
 "auth.manager-plus.seed-draw-schedules": "Only manager+ can seed draw schedules",
 "auth.manager-plus.send-booking-offers": "Only manager+ can send booking offers",
 "auth.manager-plus.send-offer-letters": "Only manager+ can send offer letters",
 "auth.manager-plus.unpublish-talent-profiles": "Only manager+ can unpublish talent profiles",
 "auth.manager-plus.update-key-results": "Only manager+ can update key results",
 "auth.manager-plus.update-reservations": "Only manager+ can update reservations",
 "auth.manager-plus.verify-documents": "Only manager+ can verify documents",
 "auth.manager-plus.withdraw-offer-letters": "Only manager+ can withdraw offer letters",
 "auth.manager-plus.work-the-door": "Only manager+ can work the door",
 "auth.manager.add-members": "Only managers and above can add members.",
 "auth.manager.archive-projects": "You Need Manager Access To Archive Projects",
 "auth.manager.assign-reviewers": "Only managers can assign reviewers.",
 "auth.manager.cancel-events": "You Need Manager Access To Cancel Events",
 "auth.manager.cancel-purchase-orders": "You Need Manager Access To Cancel Purchase Orders",
 "auth.manager.change-roles": "Only managers and above can change roles.",
 "auth.manager.create-teams": "Only managers and above can create teams.",
 "auth.manager.decide-a-time-correction": "Only managers can decide a time correction.",
 "auth.manager.decide-time-off-requests": "You need manager access to decide time-off requests",
 "auth.manager.delete-assets": "You Need Manager Access To Delete Assets",
 "auth.manager.delete-clients": "You Need Manager Access To Delete Clients",
 "auth.manager.delete-vendors": "You Need Manager Access To Delete Vendors",
 "auth.manager.edit-teams": "Only managers and above can edit teams.",
 "auth.manager.edit-the-role-catalog": "You need manager access to edit the role catalog",
 "auth.manager.import-a-schedule": "Only owners, admins, and managers can import a schedule.",
 "auth.manager.resolve-scan-misses": "You need manager access to resolve scan misses",
 "auth.manager.review-expenses": "You Need Manager Access To Review Expenses",
 "auth.manager.review-requisitions": "You Need Manager Access To Review Requisitions",
 "auth.manager.review-timesheets": "Only managers can review timesheets.",
 "auth.manager.send-proposals": "You Need Manager Access To Send Proposals",
 "auth.manager.send-purchase-orders": "You Need Manager Access To Send Purchase Orders",
 "auth.manager.transition-assignments": "You Need Manager Access To Transition Assignments",
 "auth.manager.void-invoices": "You Need Manager Access To Void Invoices",
 "auth.owner-admin.change-a-member-s-role": "Only owners and admins can change a member's role",
 "auth.owner-admin.change-compliance-settings": "Only owners and admins can change compliance settings",
 "auth.owner-admin.change-marketplace-settings": "Only owners and admins can change marketplace settings",
 "auth.owner-admin.connect-ticketing-providers": "Only owners and admins can connect ticketing providers",
 "auth.owner-admin.create-committees": "Only owners and admins can create committees",
 "auth.owner-admin.create-custom-roles": "Only owners and admins can create custom roles",
 "auth.owner-admin.create-policies": "Only owners and admins can create policies",
 "auth.owner-admin.disconnect-ticketing-providers": "Only owners and admins can disconnect ticketing providers",
 "auth.owner-admin.invite": "Only owners and admins can invite.",
 "auth.owner-admin.manage-accounting-periods": "Only owners and admins can manage accounting periods",
 "auth.owner-admin.manage-domains": "Only owners and admins can manage domains",
 "auth.owner-admin.mint-api-keys": "Only owners and admins can mint API keys",
 "auth.owner-admin.open-a-payroll-run": "Only owners and admins can open a payroll run.",
 "auth.owner-admin.resend": "Only owners and admins can resend.",
 "auth.owner-admin.revoke": "Only owners and admins can revoke.",
 "auth.owner-admin.transition-accounting-periods": "Only owners and admins can transition accounting periods",
 "auth.read-only.legend": "Your access is read-only. Ask an org admin for member access to participate.",
 "automation-is-disabled": "Automation is disabled",
 "bad-acquisition-cost": "Bad acquisition cost",
 "bad-amount": "Bad amount",
 "bad-daily-rate": "Bad daily rate",
 "bad-duration": "Bad duration",
 "bad-payment-amount": "Bad payment amount",
 "bad-received-quantity": "Bad received quantity",
 "bad-rejected-quantity": "Bad rejected quantity",
 "bad-sla-hours": "Bad SLA hours",
 "bad-threshold": "Bad threshold",
 "bad-total-value": "Bad total value",
 "batch-packet-is-missing-its-project": "Batch packet is missing its project",
 "blocks-json-is-invalid": "Blocks JSON is invalid",
 "calibration-must-be-a-positive-number": "Calibration must be a positive number",
 "check-the-fields-below": "Check the fields below",
 "checklist-already-started": "Checklist already started",
 "concurrency.application": "Application was updated concurrently. Refresh and retry",
 "concurrency.beo": "BEO changed concurrently. Refresh and retry",
 "concurrency.po-status": "PO status changed concurrently. Refresh and retry",
 "concurrency.proposal-status": "Proposal status changed concurrently. Refresh and retry",
 "concurrency.requisition": "Requisition changed concurrently. Refresh and retry",
 "concurrency.rfq": "RFQ changed concurrently. Refresh and retry",
 "concurrency.settlement": "Settlement was finalized concurrently. Refresh and retry",
 "concurrency.stale-row": "Someone else changed this record while you were editing. Reload the page to see their changes, then re-apply yours.",
 "concurrency.submission": "Submission was updated concurrently. Refresh and retry",
 "config-is-not-valid-json": "Config is not valid JSON",
 "confirm-that-you-have-reviewed-both-roles-permissions-before": "Confirm that you have reviewed both roles' permissions before merging",
 "could-not-decode-file": "Could not decode file",
 "could-not-derive-a-unique-event-slug": "Could not derive a unique event slug",
 "could-not-derive-a-unique-project-slug": "Could not derive a unique project slug",
 "could-not-enumerate-corpus-sources": "Could not enumerate corpus sources.",
 "could-not-load-timesheet": "Could not load timesheet.",
 "event-corpus-sync-unavailable": "Event corpus sync is not available yet (pending migration).",
 "could-not-resolve-the-embed-source-endpoint-origin": "Could not resolve the embed-source endpoint origin.",
 "could-not-resolve-your-party-record-in-this-workspace": "Could not resolve your party record in this workspace",
 "could-not-save-the-note": "Could not save the note.",
 "could-not-save-the-signature": "Could not save the signature.",
 "document-body-is-not-a-valid-editor-document": "Document body is not a valid editor document",
 "document-body-was-not-valid-json": "Document body was not valid JSON",
 "duration-must-be-gte-1-month": "Duration must be ≥ 1 month",
 "empty-code": "Empty code.",
 "end-must-be-after-start": "End must be after start",
 "ends-on-must-be-on-or-after-starts-on": "ends_on must be on or after starts_on",
 "enter-a-label-for-the-requirement": "Enter a label for the requirement",
 "enter-a-scan-code": "Enter a scan code",
 "every-line-needs-a-start-date": "Every Line Needs A Start Date",
 "every-report-must-be-on-this-project-s-roster": "Every report must be on this project's roster.",
 "existing-event-has-invalid-timestamps": "Existing event has invalid timestamps",
 "failed-to-create-invite": "Failed to create invite",
 "file-must-be-1-byte-to-25-mb": "File must be 1 byte to 25 MB",
 "give-the-person-a-reason-they-can-act-on": "Give the person a reason they can act on",
 "give-the-role-a-name": "Give the role a name",
 "grant-not-found-or-already-revoked": "Grant not found, or already revoked",
 "incident-is-closed-reopen-it-before-adding-corrective-work": "Incident is closed. Reopen it before adding corrective work",
 "invalid.bulk-decision-request": "Invalid bulk decision request",
 "invalid.bulk-transition-request": "Invalid Bulk Transition Request",
 "invalid.cart-payload": "Invalid Cart Payload",
 "invalid.cursor": "Invalid cursor",
 "invalid.decision": "Invalid decision",
 "invalid.fee": "Invalid fee",
 "invalid.ids": "Invalid ids",
 "invalid.input": "Invalid input",
 "invalid.layout-shape": "Invalid layout shape",
 "invalid.meeting": "Invalid meeting",
 "invalid.note": "Invalid note.",
 "invalid.request": "Invalid request",
 "invalid.scope": "Invalid scope",
 "invalid.selection": "Invalid Selection",
 "invalid.split-pct": "Invalid split %",
 "invalid.start-or-end-time": "Invalid start or end time",
 "invalid.state": "Invalid state",
 "invalid.target-phase": "Invalid target phase",
 "invalid.target-state": "Invalid target state",
 "invalid.transition": "Invalid transition",
 "invalid.trigger-kind": "invalid trigger kind",
 "label-must-be-1-160-characters": "Label must be 1-160 characters",
 "malformed-payload": "Malformed payload",
 "manager-access-required": "Manager access required",
 "manager-is-not-in-your-organization": "Manager is not in your organization",
 "manager-role-or-higher-required": "Manager role or higher required.",
 "manager-role-required": "Manager role required",
 "markup-must-be-gte-0": "Markup must be ≥ 0",
 "maximum-20-photos-per-upload": "Maximum 20 photos per upload",
 "merging-roles-merges-their-permissions-which-needs-admin-access": "Merging roles merges their permissions, which needs admin access",
 "miss-not-found-or-already-resolved": "Miss not found, or already resolved",
 "missing-concurrency-token-reload-the-page-and-try-again": "Missing concurrency token. Reload the page and try again.",
 "missing.call": "Missing call",
 "missing.connection": "Missing connection",
 "missing.dashboard-id": "Missing dashboard id",
 "missing.deal": "Missing deal",
 "missing.entry": "Missing entry",
 "missing.hold": "Missing hold",
 "missing.id": "Missing id",
 "missing.offer": "Missing offer",
 "missing.partnership": "Missing partnership",
 "missing.posting": "Missing posting",
 "missing.roster-entry": "Missing roster entry",
 "missing.steps-payload": "missing steps payload",
 "missing.talent": "Missing talent",
 "name-is-required": "Name is required",
 "need-at-least-2-options": "Need at least 2 options",
 "need-at-least-a-header-row-plus-one-data": "Need at least a header row plus one data row.",
 "no-deliverables-submittals-or-rfis-with-text-to-index": "No deliverables, submittals, or RFIs with text to index.",
 "no-walkable-sources-with-text-to-index": "No walkable sources with text to index (deliverables, submittals, RFIs, verified knowledge articles, published SOPs, event guides).",
 "not-a-member-of-this-room": "Not a member of this room",
 "not-authorized": "Not authorized",
 "not-found.account-in-org": "Account not found in this org",
 "not-found.accreditation": "Accreditation not found.",
 "not-found.accreditation-categorie": "Accreditation Categorie not found.",
 "not-found.accreditation-change": "Accreditation Change not found.",
 "not-found.accreditation-in-org": "Accreditation not found in your organization",
 "not-found.ad-manifest": "Ad Manifest not found.",
 "not-found.agency-in-org": "Agency not found in your organization",
 "not-found.application": "Application not found",
 "not-found.assessment-in-org": "Assessment not found in your organization",
 "not-found.asset": "Asset not found",
 "not-found.asset-2": "Asset not found.",
 "not-found.asset-in-org": "Asset not found in your organization",
 "not-found.assignment-in-org": "Assignment not found in your organization",
 "not-found.atom-in-org": "Atom not found in your organization",
 "not-found.automation": "Automation not found",
 "not-found.baseline-in-org": "Baseline not found in your organization",
 "not-found.batch": "Batch not found",
 "not-found.beo": "BEO not found",
 "not-found.beo-in-org": "BEO not found in your organization",
 "not-found.block": "Block not found.",
 "not-found.budget": "Budget not found.",
 "not-found.call": "Call not found",
 "not-found.catalog-item-in-org": "Catalog item not found in your organization",
 "not-found.change-order": "Change order not found",
 "not-found.channel": "Channel not found",
 "not-found.client": "Client not found.",
 "not-found.client-in-org": "Client not found in your organization",
 "not-found.contract": "Contract not found",
 "not-found.course-in-org": "Course not found in your organization",
 "not-found.credential": "Credential not found.",
 "not-found.crew-member": "Crew Member not found.",
 "not-found.crisis-alert": "Crisis Alert not found.",
 "not-found.day-sheet": "Day sheet not found",
 "not-found.deal": "Deal not found",
 "not-found.deal-in-org": "Deal not found in your organization",
 "not-found.delegation": "Delegation not found.",
 "not-found.delegation-entrie": "Delegation Entrie not found.",
 "not-found.delegation-in-org": "Delegation not found in your organization",
 "not-found.deliverable": "Deliverable not found.",
 "not-found.dispatch-run": "Dispatch Run not found.",
 "not-found.document": "Document not found.",
 "not-found.dsar-request": "Dsar Request not found.",
 "not-found.envelope": "Envelope not found",
 "not-found.environmental-event": "Environmental Event not found.",
 "not-found.estimate": "Estimate not found",
 "not-found.estimate-2": "Estimate not found.",
 "not-found.event": "Event not found",
 "not-found.event-2": "Event not found.",
 "not-found.event-in-org": "Event not found in your organization",
 "not-found.event-listing": "Event listing not found",
 "not-found.expense": "Expense not found.",
 "not-found.fabrication-order": "Fabrication Order not found.",
 "not-found.form-def": "Form Def not found.",
 "not-found.generic": "Not found",
 "not-found.goal": "Goal not found",
 "not-found.grant": "Grant not found",
 "not-found.guest-list": "Guest list not found",
 "not-found.guide": "Guide not found",
 "not-found.incident": "Incident not found",
 "not-found.incident-2": "Incident not found.",
 "not-found.inspection": "Inspection not found.",
 "not-found.insurance-policie": "Insurance Policie not found.",
 "not-found.invoice": "Invoice not found.",
 "not-found.invoice-in-org": "Invoice not found in your organization",
 "not-found.journal-entry": "Journal entry not found",
 "not-found.kb-article": "Kb Article not found.",
 "not-found.lead": "Lead not found",
 "not-found.lead-2": "Lead not found.",
 "not-found.lesson-in-org": "Lesson not found in your organization",
 "not-found.live-session-in-org": "Live session not found in your organization",
 "not-found.location-in-org": "Location not found in your organization",
 "not-found.major-incident": "Major Incident not found.",
 "not-found.medical-encounter": "Medical Encounter not found.",
 "not-found.meeting-in-org": "Meeting not found in your organization",
 "not-found.mileage-log": "Mileage Log not found.",
 "not-found.model": "Model not found.",
 "not-found.offer-letter": "Offer letter not found",
 "not-found.org-in-session": "Org not found in your session",
 "not-found.packet": "Packet not found",
 "not-found.packet-in-org": "Packet not found in your organization",
 "not-found.parent-entity-in-org": "Parent entity not found in your organization",
 "not-found.party-in-org": "Party not found in your organization",
 "not-found.person-in-org": "Person Not Found In Your Organization",
 "not-found.policy": "Policy not found",
 "not-found.program-review": "Program Review not found.",
 "not-found.project": "Project Not Found",
 "not-found.project-2": "Project not found",
 "not-found.project-3": "Project not found.",
 "not-found.project-in-org": "Project not found in your organization",
 "not-found.project-or-forbidden": "Project not found or insufficient permissions.",
 "not-found.promoter": "Promoter not found.",
 "not-found.proposal": "Proposal not found",
 "not-found.punch-item": "Punch Item not found.",
 "not-found.punch-list-in-org": "Punch list not found in your organization",
 "not-found.purchase-order": "Purchase order not found",
 "not-found.purchase-order-2": "Purchase Order not found.",
 "not-found.purchase-order-in-org": "Purchase order not found in your organization",
 "not-found.question-in-org": "Question not found in your organization",
 "not-found.questionnaire-in-org": "Questionnaire not found in your organization",
 "not-found.rate-card-item": "Rate Card Item not found.",
 "not-found.readiness-exercise": "Readiness Exercise not found.",
 "not-found.receipt": "Receipt not found",
 "not-found.rental": "Rental not found.",
 "not-found.requisition": "Requisition not found",
 "not-found.requisition-2": "Requisition not found.",
 "not-found.requisition-in-org": "Requisition not found in your organization",
 "not-found.reservation": "Reservation not found",
 "not-found.rfi": "Rfi not found.",
 "not-found.rfq": "RFQ not found",
 "not-found.risk": "Risk not found.",
 "not-found.role": "Role not found",
 "not-found.roster": "Roster not found.",
 "not-found.safeguarding-report": "Safeguarding Report not found.",
 "not-found.settlement": "Settlement not found",
 "not-found.share-link": "Share link not found",
 "not-found.sheet": "Sheet not found.",
 "not-found.sheet-set": "Sheet set not found.",
 "not-found.site-plan-in-org": "Site plan not found in your organization",
 "not-found.spec-section": "Spec section not found.",
 "not-found.sponsor-entitlement": "Sponsor Entitlement not found.",
 "not-found.submission": "Submission not found",
 "not-found.submittal": "Submittal not found.",
 "not-found.sustainability-metric": "Sustainability Metric not found.",
 "not-found.table-in-org": "Table not found in your organization",
 "not-found.takeoff": "Takeoff not found.",
 "not-found.talent-profile-in-org": "Talent profile not found in your organization",
 "not-found.task": "Task not found.",
 "not-found.team-in-org": "Team not found in your organization",
 "not-found.template-in-org": "Template not found in your organization",
 "not-found.thread": "Thread not found.",
 "not-found.ticketing-connection-in-org": "Ticketing connection not found in your organization",
 "not-found.time-entrie": "Time Entrie not found.",
 "not-found.timesheet": "Timesheet not found.",
 "not-found.tour-in-org": "Tour not found in your organization",
 "not-found.trademark": "Trademark not found.",
 "not-found.vendor": "Vendor not found",
 "not-found.vendor-2": "Vendor not found.",
 "not-found.vendor-in-org": "Vendor not found in your organization",
 "not-found.venue": "Venue not found.",
 "not-found.venue-in-org": "Venue not found in your organization",
 "not-found.visa-case": "Visa Case not found.",
 "not-found.work-order": "Work order not found",
 "not-found.workforce-deployment": "Workforce Deployment not found.",
 "not-found.workforce-member": "Workforce Member not found.",
 "offer-can-only-be-accepted-from-sent-or-countered": "Offer can only be accepted from sent or countered",
 "offer-can-t-be-sent-from-its-current-state": "Offer can't be sent from its current state",
 "only-a-draft-call-can-be-published": "Only a draft call can be published",
 "only-a-draft-posting-can-be-published": "Only a draft posting can be published",
 "only-a-live-packet-can-be-sent-go-live": "Only a live packet can be sent. Go live from the packet composer first",
 "only-a-pending-guest-can-be-checked-in": "Only a pending guest can be checked in",
 "only-a-pending-invite-can-be-resent": "Only a pending invite can be resent",
 "only-a-pending-invite-can-be-revoked": "Only a pending invite can be revoked",
 "only-a-published-call-can-be-closed": "Only a published call can be closed",
 "only-a-published-posting-can-be-closed": "Only a published posting can be closed",
 "only-a-sent-or-countered-offer-can-be-declined": "Only a sent or countered offer can be declined",
 "only-an-approved-change-order-can-post-to-budget": "Only an approved change order can post to budget. Route it through approvals first",
 "only-owner-admin-manager-can-edit-project-branding": "Only owner / admin / manager can edit project branding",
 "only-verified-articles-are-event-syncable": "Only verified articles can be synced to an event. Verify (or re-verify) the article first.",
 "ownership-pct-must-be-between-0-and-100": "Ownership % must be between 0 and 100",
 "paste-csv-or-tsv-from-the-xpms-budget-tab": "Paste CSV or TSV from the XPMS Budget tab.",
 "percentage-must-be-between-0-pct-and-100-pct": "Percentage must be between 0% and 100%",
 "pick-a-crew-member": "Pick a crew member.",
 "pick-a-manager-from-the-org-s-directory": "Pick a manager from the org's directory.",
 "pick-a-position-from-the-org-s-role-catalog": "Pick a position from the org's role catalog.",
 "pick-a-reviewer": "Pick a reviewer.",
 "pick-a-valid-decision": "Pick a valid decision.",
 "pick-a-vendor-to-award-to": "Pick a vendor to award to",
 "pick-at-least-one-module-the-subcontractor-can-reach": "Pick at least one module the subcontractor can reach.",
 "pick-at-least-one-photo": "Pick at least one photo",
 "pick-two-different-roles": "Pick two different roles",
 "po-not-found-or-missing-project": "PO not found or missing project",
 "portal-user-and-account-manager-must-be-different-people": "Portal user and account manager must be different people",
 "portal-user-is-not-in-your-organization": "Portal user is not in your organization",
 "publish-requires-at-least-one-published-lesson": "Publish requires at least one published lesson",
 "publish-requires-at-least-one-question": "Publish requires at least one question",
 "punch-list-belongs-to-a-different-project": "Punch list belongs to a different project",
 "refusing-to-demote-the-only-owner-promote-someone-to": "Refusing to demote the only owner. Promote someone to owner first.",
 "reply-body-is-required": "Reply body is required.",
 "selected-delegatee-is-not-a-member-of-this-workspace": "Selected delegatee is not a member of this workspace",
 "selected-person-is-not-a-member-of-this-workspace": "Selected person is not a member of this workspace",
 "selected-signer-is-not-a-member-of-this-workspace": "Selected signer is not a member of this workspace",
 "settlement-already-final": "Settlement already final",
 "snapshot-is-not-valid-json": "Snapshot is not valid JSON",
 "someone-else-already-decided-this-one-refresh": "Someone else already decided this one. Refresh.",
 "stage-does-not-belong-to-this-pipeline": "Stage does not belong to this pipeline",
 "submission-has-no-talent-profile-to-book": "Submission has no talent profile to book",
 "submitting-an-advance-requires-advance-request": "Submitting An Advance Requires advance:request",
 "that-change-would-create-a-reporting-loop-pick-a": "That change would create a reporting loop. Pick a different manager.",
 "that-code-is-already-active-on-another-assignment-void": "That code is already active on another assignment. Void it before re-issuing.",
 "that-line-item-does-not-belong-to-this-receipt": "That line item does not belong to this receipt's purchase order",
 "that-name-has-no-letters-or-digits-to-key": "That name has no letters or digits to key on",
 "that-person-has-been-separated-reinstate-them-before-rostering": "That person has been separated. Reinstate them before rostering.",
 "that-person-is-not-in-this-org-s-directory": "That person is not in this org's directory.",
 "that-person-is-not-in-this-organization": "That person is not in this organization.",
 "that-person-is-separated-re-engage-them-from-people": "That person is separated. Re-engage them from People before assigning.",
 "that-person-isn-t-a-member-of-this-workspace": "That person isn't a member of this workspace",
 "that-state-change-is-not-allowed": "That state change isn't allowed from the current state",
 "that-project-doesn-t-belong-to-your-org": "That project doesn't belong to your org.",
 "that-rate-card-item-is-not-available": "That rate card item is not available.",
 "that-reporting-line-would-create-a-loop-pick-a": "That reporting line would create a loop. Pick a different manager.",
 "that-request-no-longer-exists": "That request no longer exists.",
 "that-roster-no-longer-exists": "That roster no longer exists.",
 "that-user-is-already-on-this-team": "That user is already on this team.",
 "the-end-of-the-window-has-to-be-after": "The end of the window has to be after the start",
 "the-manager-must-be-on-this-project-s-roster": "The manager must be on this project's roster.",
 "the-packet-has-no-audience-contacts-to-send-to": "The packet has no audience contacts to send to",
 "the-shift-has-to-end-after-it-starts-for": "The shift has to end after it starts. For an overnight shift, set the end date to the next day.",
 "this-call-has-ended": "This call has ended",
 "this-subcontractor-is-blocked-required-compliance-documents-are-missing": "This subcontractor is blocked: required compliance documents are missing or expired.",
 "this-timesheet-was-decided-by-someone-else-refresh-and": "This timesheet was decided by someone else. Refresh and review the current state.",
 "this-vendor-already-has-a-response-edit-it-instead": "This vendor already has a response. Edit it instead.",
 "those-times-are-not-valid": "Those times are not valid.",
 "trigger-config-must-be-an-object": "trigger config must be an object",
 "unknown-state": "Unknown state",
 "unknown-submission-schema": "Unknown submission schema",
 "unknown-timezone-use-an-iana-name-like-america-new": "Unknown timezone. Use an IANA name like America/New_York",
 "use-the-leave-org-flow-to-change-your-own": "Use the leave-org flow to change your own role",
 "user-is-not-in-an-organization": "User is not in an organization",
 "user-isn-t-an-active-member-of-this-org": "User isn't an active member of this org. Invite them to the org first.",
 "vendor-already-invited-to-this-questionnaire": "Vendor already invited to this questionnaire.",
 "waste-factor-must-be-gte-0": "Waste factor must be ≥ 0",
 "you-are-not-a-member-of-this-thread": "You are not a member of this thread.",
 "you-can-t-review-your-own-timesheet-another-manager": "You can't review your own timesheet. Another manager has to decide this one.",
 "you-do-not-have-permission-to-create-meeting-notes": "You do not have permission to create meeting notes.",
 "you-do-not-have-permission-to-roster-shifts": "You do not have permission to roster shifts.",
 "your-account-is-not-linked-to-a-party-record": "Your account is not linked to a party record in this organization.",
} as const;

export type ActionErrorCode = keyof typeof ACTION_ERROR_FALLBACKS;

/**
 * Build the `{ error }` payload a server action returns for a canonical,
 * translatable failure. The `fallback` argument is the English message,
 * kept at the call site for greppability — it must match
 * ACTION_ERROR_FALLBACKS[code] (the renderer reads the catalog, not this
 * argument; a dev-mode assert keeps the two from drifting).
 */
export function actionError(code: ActionErrorCode, fallback: string): { error: string } {
  return { error: actionErrorMessage(code, fallback) };
}

/**
 * Same as `actionError` but returns the bare sentinel STRING, for call
 * sites that build the error value in string position (`actionFail(...)`,
 * ternaries against STALE_ROW_MESSAGE, custom failure shapes).
 */
export function actionErrorMessage(code: ActionErrorCode, fallback: string): string {
  if (process.env.NODE_ENV === "development" && ACTION_ERROR_FALLBACKS[code] !== fallback) {
    console.warn(
      `[errors] actionError("${code}") call-site fallback diverged from ACTION_ERROR_FALLBACKS — update one of them`,
    );
  }
  return ACTION_ERROR_PREFIX + code;
}

type TranslateFn = (key: string, vars?: Record<string, string | number>, fallback?: string) => string;

/**
 * Client-side resolution: map a State.error string to display text.
 * Sentinel strings (`@err:<code>`) resolve through `t("errors.<code>")`
 * with the English catalog entry as fallback; anything else renders as-is.
 */
export function resolveActionError(error: string, t: TranslateFn): string {
  if (!error.startsWith(ACTION_ERROR_PREFIX)) return error;
  const code = error.slice(ACTION_ERROR_PREFIX.length);
  const fallback = (ACTION_ERROR_FALLBACKS as Record<string, string>)[code] ?? code;
  return t("errors." + code, undefined, fallback);
}
