import sanitize from "sanitize-html";

/**
 * Sanitize untrusted HTML before rendering with
 * `dangerouslySetInnerHTML`. Used for proposal custom blocks, rich-text
 * editor output, and any other surface where an org member (or
 * compromised account) could persist HTML that a recipient later views.
 *
 * Policy: the subset of HTML a client proposal/deliverable/guide
 * reasonably needs — headings, lists, inline formatting, quotes,
 * images, links with `rel=noopener`, and a few data-oriented elements.
 * Script/style/iframe/object/form are always stripped; event handlers
 * (`onclick`, `onload`, …) are stripped because they're not in the
 * attribute allowlist; `javascript:` URIs die on the scheme allowlist.
 *
 * sanitize-html (htmlparser2-based, pure JS) replaced isomorphic-dompurify:
 * DOMPurify needs a DOM, and its jsdom shim refused to load inside the
 * Vercel serverless runtime — every public /proposals/[token] render
 * 500'd with "Failed to load external module jsdom" (externalizing the
 * wrapper didn't help; jsdom itself wouldn't load). sanitize-html parses
 * without a DOM, so the same allowlist works identically on server and
 * client.
 */
const ALLOWED_TAGS = [
  "a",
  "abbr",
  "b",
  "blockquote",
  "br",
  "code",
  "em",
  "figure",
  "figcaption",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "img",
  "kbd",
  "li",
  "mark",
  "ol",
  "p",
  "pre",
  "s",
  "small",
  "span",
  "strong",
  "sub",
  "sup",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "tr",
  "th",
  "td",
  "u",
  "ul",
];

const ALLOWED_ATTR = [
  "href",
  "title",
  "target",
  "rel",
  "src",
  "alt",
  "width",
  "height",
  "loading",
  "class",
  "id",
  "colspan",
  "rowspan",
];

export function sanitizeHtml(input: string): string {
  if (!input) return "";
  return sanitize(input, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: { "*": ALLOWED_ATTR },
    // Match DOMPurify's default URI policy: kill javascript:/vbscript:/
    // file: etc. on href/src.
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowedSchemesAppliedToAttributes: ["href", "src"],
    allowProtocolRelative: false,
    // Disallowed tags are dropped; script/style/textarea also drop their
    // text content (htmlparser2 nonTextTags default).
    disallowedTagsMode: "discard",
    // `rel=noopener noreferrer` enforced on every targeted anchor.
    transformTags: {
      a: (tagName, attribs) =>
        attribs.target ? { tagName, attribs: { ...attribs, rel: "noopener noreferrer" } } : { tagName, attribs },
    },
  });
}

/**
 * Strip `<script>`, `on*=` event handlers, and `javascript:` URIs from an
 * SVG string. Used as a second layer when we render an SVG generated by a
 * trusted library (`qrcode`, our own renderers) into a `<img>` data: URI —
 * the `<img>` container already sandboxes the SVG (no script execution),
 * but defense-in-depth catches any future regression in the upstream lib.
 *
 * NOT a general-purpose SVG sanitizer: it doesn't strip `<foreignObject>`,
 * `<style>`, or external references. For untrusted SVG uploads use
 * sanitizeHtml() with the SVG profile via DOMPurify. This is a tighter,
 * faster path for SVGs whose generator we already trust.
 */
export function sanitizeSvg(svg: string): string {
  return svg
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/\son[a-z]+\s*=\s*"[^"]*"/gi, "")
    .replace(/\son[a-z]+\s*=\s*'[^']*'/gi, "")
    .replace(/javascript:/gi, "");
}

/**
 * Restrict a search query string before splicing it into a PostgREST
 * filter expression (e.g. `.or("name.ilike.%${q}%,...")`). The PostgREST
 * URL grammar uses `,` as a clause separator, `.` as a field/operator
 * delimiter, and `()` for groups — any of those characters interpolated
 * raw lets a caller inject extra clauses.
 *
 * Allow-list: alphanumerics + space + a few harmless punctuations
 * (hyphen, underscore, apostrophe, ampersand) that show up in real
 * place / project names. Cap the length so we don't pass arbitrarily
 * long values to the database. Anything outside the allow-list is
 * silently dropped.
 */
export function sanitizeSearch(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9 \-_'&]/g, "").slice(0, 60);
}
