// GENERATED by scripts/gen-create-actions.mjs — do not edit.
// ⌘K "Create…" registry: every static /studio/**/new route (workflow audit F-A).
// Regenerate: npm run gen:create-actions

export type CreateAction = { href: string; label: string; group: string };

export const CONSOLE_CREATE_ACTIONS: CreateAction[] = [
  {
    href: "/studio/accommodation/blocks/new",
    label: "New Block",
    group: "Accommodation",
  },
  {
    href: "/studio/accreditation/categories/new",
    label: "New Category",
    group: "Accreditation",
  },
  {
    href: "/studio/accreditation/changes/new",
    label: "New Change",
    group: "Accreditation",
  },
  {
    href: "/studio/agency/tours/new",
    label: "New Tour",
    group: "Agency",
  },
  {
    href: "/studio/ai/agents/new",
    label: "New Agent",
    group: "AI",
  },
  {
    href: "/studio/ai/automations/new",
    label: "New Automation",
    group: "AI",
  },
  {
    href: "/studio/assets/new",
    label: "New Asset",
    group: "Assets",
  },
  {
    href: "/studio/assets/warranties/new",
    label: "New Warranty",
    group: "Assets",
  },
  {
    href: "/studio/bim/new",
    label: "New BIM",
    group: "BIM",
  },
  {
    href: "/studio/bookings/holds/new",
    label: "New Hold",
    group: "Bookings",
  },
  {
    href: "/studio/campaigns/new",
    label: "New Campaign",
    group: "Campaigns",
  },
  {
    href: "/studio/captures/new",
    label: "New Capture",
    group: "Captures",
  },
  {
    href: "/studio/clients/new",
    label: "New Client",
    group: "Clients",
  },
  {
    href: "/studio/collaborate/docs/new",
    label: "New Doc",
    group: "Collaborate",
  },
  {
    href: "/studio/collaborate/sheets/new",
    label: "New Sheet",
    group: "Collaborate",
  },
  {
    href: "/studio/collaborate/whiteboards/new",
    label: "New Whiteboard",
    group: "Collaborate",
  },
  {
    href: "/studio/commercial/sponsors/new",
    label: "New Sponsor",
    group: "Commercial",
  },
  {
    href: "/studio/comms/announcements/new",
    label: "New Announcement",
    group: "Comms",
  },
  {
    href: "/studio/comms/channels/new",
    label: "New Channel",
    group: "Comms",
  },
  {
    href: "/studio/comms/polls/new",
    label: "New Poll",
    group: "Comms",
  },
  {
    href: "/studio/comms/surveys/new",
    label: "New Survey",
    group: "Comms",
  },
  {
    href: "/studio/drawings/new",
    label: "New Drawing",
    group: "Drawings",
  },
  {
    href: "/studio/envelopes/new",
    label: "New Envelope",
    group: "Envelopes",
  },
  {
    href: "/studio/estimates/new",
    label: "New Estimate",
    group: "Estimates",
  },
  {
    href: "/studio/events/new",
    label: "New Event",
    group: "Events",
  },
  {
    href: "/studio/finance/accounts/new",
    label: "New Account",
    group: "Finance",
  },
  {
    href: "/studio/finance/budgets/new",
    label: "New Budget",
    group: "Finance",
  },
  {
    href: "/studio/finance/cost-codes/new",
    label: "New Cost Code",
    group: "Finance",
  },
  {
    href: "/studio/finance/entities/new",
    label: "New Entity",
    group: "Finance",
  },
  {
    href: "/studio/finance/expenses/new",
    label: "New Expens",
    group: "Finance",
  },
  {
    href: "/studio/finance/forecasts/new",
    label: "New Forecast",
    group: "Finance",
  },
  {
    href: "/studio/finance/invoices/new",
    label: "New Invoice",
    group: "Finance",
  },
  {
    href: "/studio/finance/ledger/new",
    label: "New Ledger",
    group: "Finance",
  },
  {
    href: "/studio/finance/lien-waivers/new",
    label: "New Lien Waiver",
    group: "Finance",
  },
  {
    href: "/studio/finance/mileage/new",
    label: "New Mileage",
    group: "Finance",
  },
  {
    href: "/studio/finance/pay-apps/new",
    label: "New Pay App",
    group: "Finance",
  },
  {
    href: "/studio/finance/payroll/new",
    label: "New Payroll",
    group: "Finance",
  },
  {
    href: "/studio/finance/periods/new",
    label: "New Period",
    group: "Finance",
  },
  {
    href: "/studio/finance/time/new",
    label: "New Time",
    group: "Finance",
  },
  {
    href: "/studio/finance/wip/new",
    label: "New WIP",
    group: "Finance",
  },
  {
    href: "/studio/forms/new",
    label: "New Form",
    group: "Forms",
  },
  {
    href: "/studio/goals/new",
    label: "New Goal",
    group: "Goals",
  },
  {
    href: "/studio/governance/approvals/delegations/new",
    label: "New Delegation",
    group: "Governance",
  },
  {
    href: "/studio/governance/approvals/policies/new",
    label: "New Policy",
    group: "Governance",
  },
  {
    href: "/studio/inspections/new",
    label: "New Inspection",
    group: "Inspections",
  },
  {
    href: "/studio/inspections/templates/new",
    label: "New Template",
    group: "Inspections",
  },
  {
    href: "/studio/knowledge/new",
    label: "New Knowledge",
    group: "Knowledge",
  },
  {
    href: "/studio/leads/new",
    label: "New Lead",
    group: "Leads",
  },
  {
    href: "/studio/legal/contracts/new",
    label: "New Contract",
    group: "Legal",
  },
  {
    href: "/studio/legal/insurance/new",
    label: "New Insurance",
    group: "Legal",
  },
  {
    href: "/studio/legal/ip/new",
    label: "New IP",
    group: "Legal",
  },
  {
    href: "/studio/legal/privacy/dsar/new",
    label: "New DSAR",
    group: "Legal",
  },
  {
    href: "/studio/locations/new",
    label: "New Location",
    group: "Locations",
  },
  {
    href: "/studio/logistics/ratecard/new",
    label: "New Ratecard",
    group: "Logistics",
  },
  {
    href: "/studio/marketplace/box-office/new",
    label: "New Box Office",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/calls/new",
    label: "New Call",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/discounts/new",
    label: "New Discount",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/discounts/promoters/new",
    label: "New Promoter",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/offers/new",
    label: "New Offer",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/postings/new",
    label: "New Posting",
    group: "Marketplace",
  },
  {
    href: "/studio/marketplace/talent/new",
    label: "New Talent",
    group: "Marketplace",
  },
  {
    href: "/studio/meetings/new",
    label: "New Meeting",
    group: "Meetings",
  },
  {
    href: "/studio/meetings/notes/new",
    label: "New Note",
    group: "Meetings",
  },
  {
    href: "/studio/operations/daily-log/new",
    label: "New Daily Log",
    group: "Operations",
  },
  {
    href: "/studio/operations/incidents/new",
    label: "New Incident",
    group: "Operations",
  },
  {
    href: "/studio/operations/maintenance/schedules/new",
    label: "New Schedule",
    group: "Operations",
  },
  {
    href: "/studio/operations/reservations/new",
    label: "New Reservation",
    group: "Operations",
  },
  {
    href: "/studio/operations/reservations/tables/new",
    label: "New Table",
    group: "Operations",
  },
  {
    href: "/studio/ops/toc/changes/new",
    label: "New Change",
    group: "Ops",
  },
  {
    href: "/studio/ops/toc/problems/new",
    label: "New Problem",
    group: "Ops",
  },
  {
    href: "/studio/participants/delegations/new",
    label: "New Delegation",
    group: "Participants",
  },
  {
    href: "/studio/participants/entries/new",
    label: "New Entry",
    group: "Participants",
  },
  {
    href: "/studio/participants/visa/new",
    label: "New Visa",
    group: "Participants",
  },
  {
    href: "/studio/people/credentials/new",
    label: "New Credential",
    group: "People",
  },
  {
    href: "/studio/people/crew/new",
    label: "New Crew",
    group: "People",
  },
  {
    href: "/studio/people/msas/new",
    label: "New Msa",
    group: "People",
  },
  {
    href: "/studio/procurement/po-change-orders/new",
    label: "New PO Change Order",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/prequalification/new",
    label: "New Prequalification",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/prequalification/questionnaires/new",
    label: "New Questionnaire",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/purchase-orders/new",
    label: "New Purchase Order",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/receiving/new",
    label: "New Receiving",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/requisitions/new",
    label: "New Requisition",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/rfqs/new",
    label: "New RFQ",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/vendors/new",
    label: "New Vendor",
    group: "Procurement",
  },
  {
    href: "/studio/procurement/wo-broadcasts/new",
    label: "New Wo Broadcast",
    group: "Procurement",
  },
  {
    href: "/studio/production/fabrication/new",
    label: "New Fabrication",
    group: "Production",
  },
  {
    href: "/studio/production/rentals/new",
    label: "New Rental",
    group: "Production",
  },
  {
    href: "/studio/production/work-orders/new",
    label: "New Work Order",
    group: "Production",
  },
  {
    href: "/studio/programs/readiness/new",
    label: "New Readiness",
    group: "Programs",
  },
  {
    href: "/studio/programs/reviews/new",
    label: "New Review",
    group: "Programs",
  },
  {
    href: "/studio/programs/risk/new",
    label: "New Risk",
    group: "Programs",
  },
  {
    href: "/studio/projects/new",
    label: "New Project",
    group: "Projects",
  },
  {
    href: "/studio/proposals/new",
    label: "New Proposal",
    group: "Proposals",
  },
  {
    href: "/studio/punch/new",
    label: "New Punch",
    group: "Punch",
  },
  {
    href: "/studio/rfis/new",
    label: "New RFI",
    group: "Rfis",
  },
  {
    href: "/studio/safety/briefings/new",
    label: "New Briefing",
    group: "Safety",
  },
  {
    href: "/studio/safety/crisis/new",
    label: "New Crisi",
    group: "Safety",
  },
  {
    href: "/studio/safety/environmental/new",
    label: "New Environmental",
    group: "Safety",
  },
  {
    href: "/studio/safety/guard-tours/new",
    label: "New Guard Tour",
    group: "Safety",
  },
  {
    href: "/studio/safety/major-incident/new",
    label: "New Major Incident",
    group: "Safety",
  },
  {
    href: "/studio/safety/medical/encounters/new",
    label: "New Encounter",
    group: "Safety",
  },
  {
    href: "/studio/safety/playbooks/new",
    label: "New Playbook",
    group: "Safety",
  },
  {
    href: "/studio/safety/safeguarding/new",
    label: "New Safeguarding",
    group: "Safety",
  },
  {
    href: "/studio/safety/threats/new",
    label: "New Threat",
    group: "Safety",
  },
  {
    href: "/studio/sales/beos/new",
    label: "New BEO",
    group: "Sales",
  },
  {
    href: "/studio/sales/diary/new",
    label: "New Diary",
    group: "Sales",
  },
  {
    href: "/studio/sales/diary/spaces/new",
    label: "New Space",
    group: "Sales",
  },
  {
    href: "/studio/schedule/baselines/new",
    label: "New Baseline",
    group: "Schedule",
  },
  {
    href: "/studio/services/requests/new",
    label: "New Request",
    group: "Services",
  },
  {
    href: "/studio/settings/account-managers/new",
    label: "New Account Manager",
    group: "Settings",
  },
  {
    href: "/studio/settings/catalog/new",
    label: "New Catalog",
    group: "Settings",
  },
  {
    href: "/studio/settings/integrations/accounting/new",
    label: "New Accounting",
    group: "Settings",
  },
  {
    href: "/studio/settings/integrations/ticketing/new",
    label: "New Ticketing",
    group: "Settings",
  },
  {
    href: "/studio/settings/job-templates/new",
    label: "New Job Template",
    group: "Settings",
  },
  {
    href: "/studio/settings/time-clock-zones/new",
    label: "New Time Clock Zone",
    group: "Settings",
  },
  {
    href: "/studio/settings/webhooks/new",
    label: "New Webhook",
    group: "Settings",
  },
  {
    href: "/studio/site-plans/new",
    label: "New Site Plan",
    group: "Site Plans",
  },
  {
    href: "/studio/specs/new",
    label: "New Spec",
    group: "Specs",
  },
  {
    href: "/studio/submittals/new",
    label: "New Submittal",
    group: "Submittals",
  },
  {
    href: "/studio/subscriptions/new",
    label: "New Subscription",
    group: "Subscriptions",
  },
  {
    href: "/studio/sustainability/carbon/new",
    label: "New Carbon",
    group: "Sustainability",
  },
  {
    href: "/studio/takeoffs/new",
    label: "New Takeoff",
    group: "Takeoffs",
  },
  {
    href: "/studio/tasks/new",
    label: "New Task",
    group: "Tasks",
  },
  {
    href: "/studio/transmittals/new",
    label: "New Transmittal",
    group: "Transmittals",
  },
  {
    href: "/studio/transport/ad/new",
    label: "New Ad",
    group: "Transport",
  },
  {
    href: "/studio/transport/dispatch/new",
    label: "New Dispatch",
    group: "Transport",
  },
  {
    href: "/studio/venues/new",
    label: "New Venue",
    group: "Venues",
  },
  {
    href: "/studio/warranties/new",
    label: "New Warranty",
    group: "Warranties",
  },
  {
    href: "/studio/workforce/badges/new",
    label: "New Badge",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/contractors/new",
    label: "New Contractor",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/deployment/new",
    label: "New Deployment",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/onboarding/new",
    label: "New Onboarding",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/recognition/new",
    label: "New Recognition",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/rosters/new",
    label: "New Roster",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/staff/new",
    label: "New Staff",
    group: "Workforce",
  },
  {
    href: "/studio/workforce/volunteers/new",
    label: "New Volunteer",
    group: "Workforce",
  },
];
