"use server";

import { createHash, randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { createClient, createServiceClient, isServiceClientAvailable } from "@/lib/supabase/server";
import { hasSupabase } from "@/lib/env";
import { emitAudit } from "@/lib/audit";
import { getSession } from "@/lib/auth";

// Server actions for /me/security/two-factor.
//
// Conventions per CLAUDE.md:
//   * `"use server"` actions live next to the page that calls them
//   * Each action returns `State = { error?: string } | null` so it plugs
//     directly into `useActionState` on the client.
//
// Recovery codes:
//   We generate 10 single-use recovery codes after a TOTP factor is verified
//   (or on demand via `regenerateRecoveryCodesAction`). Codes are sha256'd
//   before storage; plaintext is shown ONCE and returned in the action result
//   so the client can offer "Download codes". Re-generating discards the old
//   set entirely, matching every popular MFA implementation (Stripe, GitHub).

export type State = { error?: string } | null;

export type EnrollResult =
  | { error: string }
  | { ok: true; factorId: string; secret: string; qrSvg: string; uri: string };

export type VerifyResult = { error: string } | { ok: true; recoveryCodes: string[] };

export type RegenerateResult = { error: string } | { ok: true; recoveryCodes: string[] };

// `mfa_recovery_codes` is added by 20260504000024 — types haven't been
// regenerated yet, so we type the relevant slice of the client locally and
// cast at the call site (mirrors the push_subscriptions pattern).
type RecoveryCodesClient = {
  from: (table: "mfa_recovery_codes") => {
    delete: () => {
      eq: (
        col: string,
        val: string,
      ) => Promise<{ error: { message: string } | null }> & {
        lt: (col: string, val: string) => Promise<{ error: { message: string } | null }>;
      };
    };
    insert: (rows: Array<{ user_id: string; code_hash: string }>) => Promise<{ error: { message: string } | null }>;
  };
};

const RECOVERY_CODE_COUNT = 10;

function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

/**
 * Generate `count` recovery codes. Each code is 16 hex chars (64 bits) split
 * with a hyphen for readability — enough entropy that brute-forcing is
 * infeasible against the unauthenticated rate-limit, and short enough to type.
 */
function generateRecoveryCodes(count: number): string[] {
  return Array.from({ length: count }, () => {
    const raw = randomBytes(8).toString("hex"); // 16 hex chars
    return `${raw.slice(0, 8)}-${raw.slice(8)}`;
  });
}

import { sanitizeSvg } from "@/lib/sanitize";

/**
 * Render a TOTP otpauth URI as a sanitized SVG, returned as a `data:` URI
 * the client embeds via `<img src=...>`.
 *
 * Why a data: URI and not inline `dangerouslySetInnerHTML`?
 *   The SVG is generated by the `qrcode` package from a controlled
 *   otpauth:// URI we built — but defense in depth says don't inline
 *   third-party HTML when a safer container exists. SVG-in-`<img>` runs
 *   in passive image mode: any `<script>` or event handler the SVG
 *   carries is ignored by the browser. sanitizeSvg() strips
 *   script/handler patterns as a second layer.
 */
async function renderQrSvg(uri: string): Promise<string> {
  const QRCode = await import("qrcode");
  const raw: string = await QRCode.toString(uri, { type: "svg", margin: 1, width: 240 });
  const sanitized = sanitizeSvg(raw);
  // base64-encode so the URI is opaque + caching-friendly. The Buffer call
  // is server-only so this is safe in a "use server" file.
  const b64 = Buffer.from(sanitized, "utf8").toString("base64");
  return `data:image/svg+xml;base64,${b64}`;
}

// ────────────────────────────────────────────────────────────────────
// Enrollment — step 1: enroll a TOTP factor and return QR + secret
// ────────────────────────────────────────────────────────────────────

export async function enrollMfaAction(): Promise<EnrollResult> {
  if (!hasSupabase) return { error: "Supabase is not configured." };
  const session = await getSession();
  if (!session) return { error: "Sign in to enroll a second factor." };

  const supabase = await createClient();
  const { data, error } = await supabase.auth.mfa.enroll({
    factorType: "totp",
    friendlyName: `Authenticator (${new Date().toISOString().slice(0, 10)})`,
  });
  if (error || !data) {
    return { error: error?.message ?? "Couldn't start enrollment" };
  }

  const totp = data.totp;
  if (!totp) return { error: "Supabase did not return TOTP details" };

  let qrSvg = "";
  try {
    qrSvg = await renderQrSvg(totp.uri);
  } catch {
    // Fall back to text-only display in the client. The secret is the
    // canonical input — most authenticator apps accept a manual secret entry.
    qrSvg = "";
  }

  return { ok: true, factorId: data.id, secret: totp.secret, qrSvg, uri: totp.uri };
}

// ────────────────────────────────────────────────────────────────────
// Enrollment — step 2: verify the 6-digit code, generate recovery codes
// ────────────────────────────────────────────────────────────────────

export async function verifyEnrollmentAction(factorId: string, code: string): Promise<VerifyResult> {
  if (!hasSupabase) return { error: "Supabase is not configured." };
  if (!factorId) return { error: "Missing factor. Restart enrollment." };
  if (!/^\d{6}$/.test(code.trim())) return { error: "Enter the 6-digit code from your authenticator app." };

  const session = await getSession();
  if (!session) return { error: "Sign in to verify your second factor." };

  const supabase = await createClient();
  const challenge = await supabase.auth.mfa.challenge({ factorId });
  if (challenge.error || !challenge.data) {
    return { error: challenge.error?.message ?? "Couldn't issue MFA challenge" };
  }
  const verify = await supabase.auth.mfa.verify({
    factorId,
    challengeId: challenge.data.id,
    code: code.trim(),
  });
  if (verify.error) {
    return { error: verify.error.message };
  }

  // Generate recovery codes — only stored hashed.
  const codes = generateRecoveryCodes(RECOVERY_CODE_COUNT);
  if (isServiceClientAvailable()) {
    const admin = createServiceClient() as unknown as RecoveryCodesClient;
    // Capture the cutoff BEFORE inserting so we only delete codes
    // that pre-date this batch. If the insert fails the user keeps
    // any prior codes; without this ordering a delete-then-insert
    // failure would leave zero codes for the user.
    const cutoff = new Date().toISOString();
    const { error: insErr } = await admin
      .from("mfa_recovery_codes")
      .insert(codes.map((c) => ({ user_id: session.userId, code_hash: sha256(c) })));
    if (insErr) return { error: `Couldn't save recovery codes: ${insErr.message}` };
    // Now safe to wipe prior codes (created_at < cutoff). A failure
    // here is non-fatal — user has a fresh valid set; old codes
    // would still resolve to this user but get superseded on next
    // regenerate.
    await admin.from("mfa_recovery_codes").delete().eq("user_id", session.userId).lt("created_at", cutoff);
  }

  await emitAudit({
    actorId: session.userId,
    orgId: session.orgId,
    actorEmail: session.email,
    action: "auth.mfa.enabled",
    targetTable: "auth.mfa_factors",
    targetId: factorId,
    metadata: { factorType: "totp" },
  });

  revalidatePath("/me/security");
  revalidatePath("/me/security/two-factor");

  return { ok: true, recoveryCodes: codes };
}

// ────────────────────────────────────────────────────────────────────
// Unenroll — remove a factor
// ────────────────────────────────────────────────────────────────────

export async function unenrollMfaAction(factorId: string): Promise<State> {
  if (!hasSupabase) return { error: "Supabase is not configured." };
  if (!factorId) return { error: "Missing factor id" };

  const session = await getSession();
  if (!session) return { error: "Sign in to remove a second factor." };

  const supabase = await createClient();

  // Last-factor self-lockout guard. If the org has require_2fa_for the
  // user's role AND this is their last verified TOTP factor, removing
  // it immediately locks them out on the next request (the MFA gate
  // in proxy.ts bounces to /mfa/challenge but there's nothing to
  // challenge against). Refuse and tell them to enroll a replacement
  // first.
  if (session.orgId) {
    const { data: orgRow } = await supabase
      .from("orgs")
      .select("require_2fa_for")
      .eq("id", session.orgId)
      .maybeSingle();
    const requireMap =
      ((orgRow as { require_2fa_for?: Record<string, boolean> } | null)?.require_2fa_for as
        | Record<string, boolean>
        | undefined) ?? {};
    if (requireMap[session.role]) {
      // Count remaining verified factors. Supabase returns all factors
      // including unverified — only count the ones that would still
      // satisfy the MFA gate after this unenroll.
      const { data: factorList } = await supabase.auth.mfa.listFactors();
      const verified = (factorList?.totp ?? []).filter((f) => f.status === "verified" && f.id !== factorId);
      if (verified.length === 0) {
        return {
          error:
            "Your org requires 2FA for your role. Enroll another factor before removing this one or you'll be locked out.",
        };
      }
    }
  }

  const { error } = await supabase.auth.mfa.unenroll({ factorId });
  if (error) return { error: error.message };

  // Drop recovery codes once the last TOTP factor is gone. Done after the
  // unenroll succeeds so a partial failure leaves the codes in place.
  if (isServiceClientAvailable()) {
    const admin = createServiceClient() as unknown as RecoveryCodesClient;
    await admin.from("mfa_recovery_codes").delete().eq("user_id", session.userId);
  }

  await emitAudit({
    actorId: session.userId,
    orgId: session.orgId,
    actorEmail: session.email,
    action: "auth.mfa.disabled",
    targetTable: "auth.mfa_factors",
    targetId: factorId,
  });

  revalidatePath("/me/security");
  revalidatePath("/me/security/two-factor");
  return null;
}

// ────────────────────────────────────────────────────────────────────
// Regenerate recovery codes
// ────────────────────────────────────────────────────────────────────

export async function regenerateRecoveryCodesAction(): Promise<RegenerateResult> {
  if (!hasSupabase) return { error: "Supabase is not configured." };
  const session = await getSession();
  if (!session) return { error: "Sign in to regenerate recovery codes." };

  if (!isServiceClientAvailable()) {
    return { error: "Recovery codes require the service-role client. Set SUPABASE_SERVICE_ROLE_KEY." };
  }

  const codes = generateRecoveryCodes(RECOVERY_CODE_COUNT);
  const admin = createServiceClient() as unknown as RecoveryCodesClient;
  // Insert NEW codes first, then delete the prior batch. If the
  // insert fails the user keeps their existing valid codes; the
  // prior delete-then-insert pattern would have wiped all codes
  // and then failed, leaving the user locked out of recovery.
  const cutoff = new Date().toISOString();
  const { error } = await admin
    .from("mfa_recovery_codes")
    .insert(codes.map((c) => ({ user_id: session.userId, code_hash: sha256(c) })));
  if (error) return { error: error.message };
  await admin.from("mfa_recovery_codes").delete().eq("user_id", session.userId).lt("created_at", cutoff);

  // P0 hardening — emit an audit row for the regeneration. Recovery
  // codes are sensitive material; without an audit trail the user
  // (and security review) can't tell when codes were rotated. Hard
  // delete on prior codes is correct (soft delete leaves redeemable
  // secrets findable); the audit row preserves the forensic record.
  await emitAudit({
    actorId: session.userId,
    orgId: session.orgId,
    actorEmail: session.email,
    action: "auth.mfa.recovery_codes_regenerated",
    targetTable: "mfa_recovery_codes",
    targetId: session.userId,
    metadata: { count: codes.length },
  });

  return { ok: true, recoveryCodes: codes };
}
