/**
 * Permanent ban: `as any` is forbidden in src/ except for explicitly
 * allowlisted exceptions (none today). The codebase's centralized
 * typed-loose escape hatch is `LooseSupabase` (src/lib/supabase/loose.ts).
 * Reach for that, not `as any`.
 *
 * This test fails on regression — adding `as any` anywhere under src/
 * (outside the generated database.types.ts and the test files
 * themselves) breaks CI.
 *
 * Why a test rather than ESLint? The repo currently has eslint
 * enabled with @typescript-eslint, but per-rule config drift is easier
 * to inadvertently weaken than a deterministic Vitest assertion. This
 * test is the single source of truth for the ban.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { sync as glob } from "fast-glob";
import { relative } from "node:path";

const REPO_ROOT = new URL("../../", import.meta.url).pathname;

// Files allowed to keep `as any`. Empty for now — the rule is strict.
// Add an entry here only when (a) you've documented WHY in a comment
// at the call site and (b) a code reviewer has signed off.
const ALLOW = new Set<string>([
  // Generated by Supabase CLI from the live schema; not hand-edited.
  "src/lib/supabase/database.types.ts",
  // The rule itself names the regex in a doc string + the exception
  // policy mention above; self-reference must not trip the test.
  "src/app/no-as-any.test.ts",
]);

// Match `as any` when used as a TypeScript type assertion (with
// optional whitespace). Excludes:
//   - prose containing "as any" in plain English
//   - parameter names like `as_any` (no space + underscore)
//   - the substring inside a longer identifier
const AS_ANY_TYPE_ASSERT = /\bas\s+any\b/;

function isLineCommentOrInsideString(line: string, matchIndex: number): boolean {
  const before = line.slice(0, matchIndex);
  // Single-line comment
  if (/^\s*\/\//.test(line)) return true;
  // Inside a // comment after code
  if (before.includes("//")) return true;
  // Inside a single-line block comment /* ... */
  if (/\/\*[^*]*$/.test(before) && line.slice(matchIndex).includes("*/")) return true;
  // Inside a string literal — naive but good enough for the
  // import/export/source we scan. We count unescaped quotes before the
  // match; odd → inside a string.
  const dq = (before.match(/(?<!\\)"/g) || []).length;
  const sq = (before.match(/(?<!\\)'/g) || []).length;
  const bt = (before.match(/(?<!\\)`/g) || []).length;
  if (dq % 2 === 1 || sq % 2 === 1 || bt % 2 === 1) return true;
  return false;
}

describe("Codebase hygiene — `as any` ban", () => {
  it("zero `as any` type assertions in src/ (excluding generated types + this test)", () => {
    const files = glob(["src/**/*.ts", "src/**/*.tsx"], { cwd: REPO_ROOT, absolute: true });
    const offenders: Array<{ file: string; line: number; text: string }> = [];

    for (const file of files) {
      const rel = relative(REPO_ROOT, file);
      if (ALLOW.has(rel)) continue;
      const content = readFileSync(file, "utf8");
      const lines = content.split("\n");

      // Skip multi-line `/* ... */` block-comment regions.
      let inBlockComment = false;
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i]!;
        const blockStart = line.indexOf("/*");
        const blockEnd = line.indexOf("*/");

        // Track block comment state across lines (rough — sufficient
        // for the patterns we care about).
        if (inBlockComment) {
          if (blockEnd >= 0) inBlockComment = false;
          continue;
        }
        if (blockStart >= 0 && blockEnd < 0) {
          inBlockComment = true;
          continue;
        }

        const m = line.match(AS_ANY_TYPE_ASSERT);
        if (!m || m.index === undefined) continue;
        if (isLineCommentOrInsideString(line, m.index)) continue;
        offenders.push({ file: rel, line: i + 1, text: line.trim() });
      }
    }

    expect(
      offenders,
      `Found ${offenders.length} \`as any\` violations:\n` +
        offenders.map((o) => `  ${o.file}:${o.line}\n    ${o.text}`).join("\n") +
        "\n\nUse @/lib/supabase/loose#LooseSupabase for dynamic-table dispatch, " +
        "type guards for SDK content unions, or proper type assertions like " +
        "`as unknown as { specific: shape }`. Do not use `as any`.",
    ).toEqual([]);
  });
});
