// GENERATED by scripts/gen-create-actions.mjs — do not edit.
// ⌘K "Create…" registry: every static /console/**/new route (workflow audit F-A).
// Regenerate: npm run gen:create-actions

export type CreateAction = { href: string; label: string; group: string };

export const CONSOLE_CREATE_ACTIONS: CreateAction[] = [
  {
    "href": "/console/accommodation/blocks/new",
    "label": "New Block",
    "group": "Accommodation"
  },
  {
    "href": "/console/accreditation/categories/new",
    "label": "New Category",
    "group": "Accreditation"
  },
  {
    "href": "/console/accreditation/changes/new",
    "label": "New Change",
    "group": "Accreditation"
  },
  {
    "href": "/console/agency/tours/new",
    "label": "New Tour",
    "group": "Agency"
  },
  {
    "href": "/console/ai/agents/new",
    "label": "New Agent",
    "group": "AI"
  },
  {
    "href": "/console/ai/automations/new",
    "label": "New Automation",
    "group": "AI"
  },
  {
    "href": "/console/bim/new",
    "label": "New BIM",
    "group": "BIM"
  },
  {
    "href": "/console/bookings/holds/new",
    "label": "New Hold",
    "group": "Bookings"
  },
  {
    "href": "/console/campaigns/new",
    "label": "New Campaign",
    "group": "Campaigns"
  },
  {
    "href": "/console/captures/new",
    "label": "New Capture",
    "group": "Captures"
  },
  {
    "href": "/console/clients/new",
    "label": "New Client",
    "group": "Clients"
  },
  {
    "href": "/console/collaborate/docs/new",
    "label": "New Doc",
    "group": "Collaborate"
  },
  {
    "href": "/console/collaborate/sheets/new",
    "label": "New Sheet",
    "group": "Collaborate"
  },
  {
    "href": "/console/collaborate/whiteboards/new",
    "label": "New Whiteboard",
    "group": "Collaborate"
  },
  {
    "href": "/console/commercial/sponsors/new",
    "label": "New Sponsor",
    "group": "Commercial"
  },
  {
    "href": "/console/comms/announcements/new",
    "label": "New Announcement",
    "group": "Comms"
  },
  {
    "href": "/console/comms/polls/new",
    "label": "New Poll",
    "group": "Comms"
  },
  {
    "href": "/console/comms/surveys/new",
    "label": "New Survey",
    "group": "Comms"
  },
  {
    "href": "/console/contracts/new",
    "label": "New Contract",
    "group": "Contracts"
  },
  {
    "href": "/console/drawings/new",
    "label": "New Drawing",
    "group": "Drawings"
  },
  {
    "href": "/console/envelopes/new",
    "label": "New Envelope",
    "group": "Envelopes"
  },
  {
    "href": "/console/estimates/new",
    "label": "New Estimate",
    "group": "Estimates"
  },
  {
    "href": "/console/events/new",
    "label": "New Event",
    "group": "Events"
  },
  {
    "href": "/console/finance/budgets/new",
    "label": "New Budget",
    "group": "Finance"
  },
  {
    "href": "/console/finance/cost-codes/new",
    "label": "New Cost Code",
    "group": "Finance"
  },
  {
    "href": "/console/finance/entities/new",
    "label": "New Entity",
    "group": "Finance"
  },
  {
    "href": "/console/finance/expenses/new",
    "label": "New Expens",
    "group": "Finance"
  },
  {
    "href": "/console/finance/forecasts/new",
    "label": "New Forecast",
    "group": "Finance"
  },
  {
    "href": "/console/finance/invoices/new",
    "label": "New Invoice",
    "group": "Finance"
  },
  {
    "href": "/console/finance/lien-waivers/new",
    "label": "New Lien Waiver",
    "group": "Finance"
  },
  {
    "href": "/console/finance/mileage/new",
    "label": "New Mileage",
    "group": "Finance"
  },
  {
    "href": "/console/finance/pay-apps/new",
    "label": "New Pay App",
    "group": "Finance"
  },
  {
    "href": "/console/finance/payroll/new",
    "label": "New Payroll",
    "group": "Finance"
  },
  {
    "href": "/console/finance/periods/new",
    "label": "New Period",
    "group": "Finance"
  },
  {
    "href": "/console/finance/time/new",
    "label": "New Time",
    "group": "Finance"
  },
  {
    "href": "/console/finance/wip/new",
    "label": "New WIP",
    "group": "Finance"
  },
  {
    "href": "/console/forms/new",
    "label": "New Form",
    "group": "Forms"
  },
  {
    "href": "/console/goals/new",
    "label": "New Goal",
    "group": "Goals"
  },
  {
    "href": "/console/inspections/new",
    "label": "New Inspection",
    "group": "Inspections"
  },
  {
    "href": "/console/inspections/templates/new",
    "label": "New Template",
    "group": "Inspections"
  },
  {
    "href": "/console/knowledge/new",
    "label": "New Knowledge",
    "group": "Knowledge"
  },
  {
    "href": "/console/leads/new",
    "label": "New Lead",
    "group": "Leads"
  },
  {
    "href": "/console/legal/insurance/new",
    "label": "New Insurance",
    "group": "Legal"
  },
  {
    "href": "/console/legal/ip/new",
    "label": "New IP",
    "group": "Legal"
  },
  {
    "href": "/console/legal/privacy/dsar/new",
    "label": "New DSAR",
    "group": "Legal"
  },
  {
    "href": "/console/legend/engine/rules/new",
    "label": "New Rule",
    "group": "Legend"
  },
  {
    "href": "/console/legend/resources/new",
    "label": "New Resource",
    "group": "Legend"
  },
  {
    "href": "/console/legend/resources/collections/new",
    "label": "New Collection",
    "group": "Legend"
  },
  {
    "href": "/console/legend/signage/new",
    "label": "New Signage",
    "group": "Legend"
  },
  {
    "href": "/console/locations/new",
    "label": "New Location",
    "group": "Locations"
  },
  {
    "href": "/console/logistics/ratecard/new",
    "label": "New Ratecard",
    "group": "Logistics"
  },
  {
    "href": "/console/marketplace/box-office/new",
    "label": "New Box Office",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/calls/new",
    "label": "New Call",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/discounts/new",
    "label": "New Discount",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/discounts/promoters/new",
    "label": "New Promoter",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/offers/new",
    "label": "New Offer",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/postings/new",
    "label": "New Posting",
    "group": "Marketplace"
  },
  {
    "href": "/console/marketplace/talent/new",
    "label": "New Talent",
    "group": "Marketplace"
  },
  {
    "href": "/console/meetings/new",
    "label": "New Meeting",
    "group": "Meetings"
  },
  {
    "href": "/console/meetings/notes/new",
    "label": "New Note",
    "group": "Meetings"
  },
  {
    "href": "/console/operations/daily-log/new",
    "label": "New Daily Log",
    "group": "Operations"
  },
  {
    "href": "/console/operations/incidents/new",
    "label": "New Incident",
    "group": "Operations"
  },
  {
    "href": "/console/operations/maintenance/schedules/new",
    "label": "New Schedule",
    "group": "Operations"
  },
  {
    "href": "/console/operations/reservations/new",
    "label": "New Reservation",
    "group": "Operations"
  },
  {
    "href": "/console/operations/reservations/tables/new",
    "label": "New Table",
    "group": "Operations"
  },
  {
    "href": "/console/ops/toc/changes/new",
    "label": "New Change",
    "group": "Ops"
  },
  {
    "href": "/console/ops/toc/problems/new",
    "label": "New Problem",
    "group": "Ops"
  },
  {
    "href": "/console/participants/delegations/new",
    "label": "New Delegation",
    "group": "Participants"
  },
  {
    "href": "/console/participants/entries/new",
    "label": "New Entry",
    "group": "Participants"
  },
  {
    "href": "/console/participants/visa/new",
    "label": "New Visa",
    "group": "Participants"
  },
  {
    "href": "/console/people/credentials/new",
    "label": "New Credential",
    "group": "People"
  },
  {
    "href": "/console/people/crew/new",
    "label": "New Crew",
    "group": "People"
  },
  {
    "href": "/console/people/msas/new",
    "label": "New Msa",
    "group": "People"
  },
  {
    "href": "/console/procurement/po-change-orders/new",
    "label": "New PO Change Order",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/prequalification/new",
    "label": "New Prequalification",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/prequalification/questionnaires/new",
    "label": "New Questionnaire",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/purchase-orders/new",
    "label": "New Purchase Order",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/requisitions/new",
    "label": "New Requisition",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/rfqs/new",
    "label": "New RFQ",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/vendors/new",
    "label": "New Vendor",
    "group": "Procurement"
  },
  {
    "href": "/console/procurement/wo-broadcasts/new",
    "label": "New Wo Broadcast",
    "group": "Procurement"
  },
  {
    "href": "/console/production/equipment/new",
    "label": "New Equipment",
    "group": "Production"
  },
  {
    "href": "/console/production/fabrication/new",
    "label": "New Fabrication",
    "group": "Production"
  },
  {
    "href": "/console/production/rentals/new",
    "label": "New Rental",
    "group": "Production"
  },
  {
    "href": "/console/programs/readiness/new",
    "label": "New Readiness",
    "group": "Programs"
  },
  {
    "href": "/console/programs/reviews/new",
    "label": "New Review",
    "group": "Programs"
  },
  {
    "href": "/console/programs/risk/new",
    "label": "New Risk",
    "group": "Programs"
  },
  {
    "href": "/console/projects/new",
    "label": "New Project",
    "group": "Projects"
  },
  {
    "href": "/console/proposals/new",
    "label": "New Proposal",
    "group": "Proposals"
  },
  {
    "href": "/console/punch/new",
    "label": "New Punch",
    "group": "Punch"
  },
  {
    "href": "/console/rfis/new",
    "label": "New RFI",
    "group": "Rfis"
  },
  {
    "href": "/console/safety/briefings/new",
    "label": "New Briefing",
    "group": "Safety"
  },
  {
    "href": "/console/safety/crisis/new",
    "label": "New Crisi",
    "group": "Safety"
  },
  {
    "href": "/console/safety/environmental/new",
    "label": "New Environmental",
    "group": "Safety"
  },
  {
    "href": "/console/safety/guard-tours/new",
    "label": "New Guard Tour",
    "group": "Safety"
  },
  {
    "href": "/console/safety/major-incident/new",
    "label": "New Major Incident",
    "group": "Safety"
  },
  {
    "href": "/console/safety/medical/encounters/new",
    "label": "New Encounter",
    "group": "Safety"
  },
  {
    "href": "/console/safety/playbooks/new",
    "label": "New Playbook",
    "group": "Safety"
  },
  {
    "href": "/console/safety/safeguarding/new",
    "label": "New Safeguarding",
    "group": "Safety"
  },
  {
    "href": "/console/safety/threats/new",
    "label": "New Threat",
    "group": "Safety"
  },
  {
    "href": "/console/sales/beos/new",
    "label": "New BEO",
    "group": "Sales"
  },
  {
    "href": "/console/sales/diary/new",
    "label": "New Diary",
    "group": "Sales"
  },
  {
    "href": "/console/sales/diary/spaces/new",
    "label": "New Space",
    "group": "Sales"
  },
  {
    "href": "/console/schedule/baselines/new",
    "label": "New Baseline",
    "group": "Schedule"
  },
  {
    "href": "/console/services/requests/new",
    "label": "New Request",
    "group": "Services"
  },
  {
    "href": "/console/settings/account-managers/new",
    "label": "New Account Manager",
    "group": "Settings"
  },
  {
    "href": "/console/settings/catalog/new",
    "label": "New Catalog",
    "group": "Settings"
  },
  {
    "href": "/console/settings/integrations/accounting/new",
    "label": "New Accounting",
    "group": "Settings"
  },
  {
    "href": "/console/settings/integrations/ticketing/new",
    "label": "New Ticketing",
    "group": "Settings"
  },
  {
    "href": "/console/settings/time-clock-zones/new",
    "label": "New Time Clock Zone",
    "group": "Settings"
  },
  {
    "href": "/console/settings/webhooks/new",
    "label": "New Webhook",
    "group": "Settings"
  },
  {
    "href": "/console/site-plans/new",
    "label": "New Site Plan",
    "group": "Site Plans"
  },
  {
    "href": "/console/specs/new",
    "label": "New Spec",
    "group": "Specs"
  },
  {
    "href": "/console/submittals/new",
    "label": "New Submittal",
    "group": "Submittals"
  },
  {
    "href": "/console/subscriptions/new",
    "label": "New Subscription",
    "group": "Subscriptions"
  },
  {
    "href": "/console/sustainability/carbon/new",
    "label": "New Carbon",
    "group": "Sustainability"
  },
  {
    "href": "/console/takeoffs/new",
    "label": "New Takeoff",
    "group": "Takeoffs"
  },
  {
    "href": "/console/tasks/new",
    "label": "New Task",
    "group": "Tasks"
  },
  {
    "href": "/console/transmittals/new",
    "label": "New Transmittal",
    "group": "Transmittals"
  },
  {
    "href": "/console/transport/ad/new",
    "label": "New Ad",
    "group": "Transport"
  },
  {
    "href": "/console/transport/dispatch/new",
    "label": "New Dispatch",
    "group": "Transport"
  },
  {
    "href": "/console/venues/new",
    "label": "New Venue",
    "group": "Venues"
  },
  {
    "href": "/console/warranties/new",
    "label": "New Warranty",
    "group": "Warranties"
  },
  {
    "href": "/console/workforce/badges/new",
    "label": "New Badge",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/contractors/new",
    "label": "New Contractor",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/courses/new",
    "label": "New Cours",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/deployment/new",
    "label": "New Deployment",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/onboarding/new",
    "label": "New Onboarding",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/recognition/new",
    "label": "New Recognition",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/rosters/new",
    "label": "New Roster",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/staff/new",
    "label": "New Staff",
    "group": "Workforce"
  },
  {
    "href": "/console/workforce/volunteers/new",
    "label": "New Volunteer",
    "group": "Workforce"
  }
];
