-- Tighten storage RLS to gate uploads AND reads on org-folder
-- membership. The earlier 20260509100009 version was authored but
-- never applied (modifying policies on storage.objects requires the
-- `supabase_admin` role which neither the MCP key nor `supabase
-- migrate` posseses). This is the canonical replacement.
--
-- ⚠️ APPLY VIA DASHBOARD → SQL EDITOR (logged in as the project's
-- superuser owner). MCP attempts return:
--     ERROR:  42501: must be owner of relation objects
--
-- Three changes vs prior live state:
--
-- 1. UPLOAD policy: split the permissive `storage_authenticated_upload`
--    into two — service-role-only buckets (proposals, receipts,
--    credentials, branding, procore-parity) keep a wide-open shape
--    because only compileAndStore writes them; user-direct buckets
--    (advancing, incident-photos) require the path's first folder to
--    match a member-org of auth.uid() AND that membership must not
--    be soft-deleted.
--
-- 2. READ policy: `storage_signed_read` was permissive across all
--    seven buckets — any authenticated user could read any object if
--    they could guess the path. Replaced with org-folder gating: the
--    first folder of the object name must be a member-org of
--    auth.uid(). Signed URLs (generated by service-role) bypass RLS
--    and continue to work for the existing app paths.
--
-- 3. Soft-delete guards on memberships in both new policies — an
--    offboarded user's lingering session must not be able to upload
--    or read inside their old org's folder.

drop policy if exists storage_authenticated_upload on storage.objects;
drop policy if exists storage_org_scoped_upload on storage.objects;
drop policy if exists storage_service_role_buckets_upload on storage.objects;
drop policy if exists storage_signed_read on storage.objects;
drop policy if exists storage_org_scoped_read on storage.objects;

-- Service-role-only buckets — server jobs (PDF generators) write
-- here via service_role; the authenticated INSERT policy is kept
-- permissive within those buckets so a future server-action that
-- writes via the session client doesn't 403 mysteriously.
create policy storage_service_role_buckets_upload on storage.objects
  for insert to authenticated
  with check (
    bucket_id = any (array[
      'proposals'::text,
      'receipts'::text,
      'credentials'::text,
      'branding'::text,
      'procore-parity'::text
    ])
  );

-- User-direct upload buckets: path[1] must be a member-org.
create policy storage_org_scoped_upload on storage.objects
  for insert to authenticated
  with check (
    bucket_id = any (array['advancing'::text, 'incident-photos'::text])
    and exists (
      select 1
      from public.memberships m
      where m.user_id = (select auth.uid())
        and m.org_id::text = (storage.foldername(name))[1]
        and m.deleted_at is null
    )
  );

-- READ: same org-folder gate. Replaces the wide-open
-- `storage_signed_read` policy. Signed URLs (which bypass RLS) still
-- work for legitimate share-link flows.
create policy storage_org_scoped_read on storage.objects
  for select to authenticated
  using (
    bucket_id = any (array[
      'advancing'::text,
      'receipts'::text,
      'proposals'::text,
      'credentials'::text,
      'branding'::text,
      'incident-photos'::text,
      'procore-parity'::text
    ])
    and exists (
      select 1
      from public.memberships m
      where m.user_id = (select auth.uid())
        and m.org_id::text = (storage.foldername(name))[1]
        and m.deleted_at is null
    )
  );

comment on policy storage_service_role_buckets_upload on storage.objects is
  'Permissive insert for service-role-only buckets (PDF generators write via compileAndStore in src/lib/pdf/render.ts).';

comment on policy storage_org_scoped_upload on storage.objects is
  'Org-folder enforcement for user-direct upload buckets. Path[1] must be one of the user''s ACTIVE org_ids (deleted_at IS NULL).';

comment on policy storage_org_scoped_read on storage.objects is
  'Org-folder enforcement for direct authenticated reads. Path[1] must be one of the user''s ACTIVE org_ids. Signed-URL reads (generated by service_role) bypass RLS and remain functional.';
