-- Performance advisor remediation: cover every foreign key with an index, and
-- drop redundant duplicate indexes (the constraint-backed / identical twin is kept).
-- Derived directly from the pg catalog (pg_constraint contype='f' lacking a
-- left-prefix covering index; pg_index groups identical on indkey+indpred+indexprs).
-- All statements idempotent. Supersedes ad-hoc FK indexing; closes 143 unindexed FKs + 12 dupes.

create index if not exists idx_achievement_awards_achievement_id on achievement_awards (achievement_id);
create index if not exists idx_achievement_awards_user_id on achievement_awards (user_id);
create index if not exists idx_achievements_created_by on achievements (created_by);
create index if not exists idx_assessment_attempts_assessment_id on assessment_attempts (assessment_id);
create index if not exists idx_assessment_attempts_user_id on assessment_attempts (user_id);
create index if not exists idx_assessment_questions_assessment_id on assessment_questions (assessment_id);
create index if not exists idx_assessments_course_id on assessments (course_id);
create index if not exists idx_assessments_lesson_id on assessments (lesson_id);
create index if not exists idx_beo_line_items_beo_id on beo_line_items (beo_id);
create index if not exists idx_beos_client_id on beos (client_id);
create index if not exists idx_beos_created_by on beos (created_by);
create index if not exists idx_beos_project_id on beos (project_id);
create index if not exists idx_bridge_atom_metric_metric_id on bridge_atom_metric (metric_id);
create index if not exists idx_bridge_atom_permit_permit_id on bridge_atom_permit (permit_id);
create index if not exists idx_bridge_package_atom_component_atom_id on bridge_package_atom (component_atom_id);
create index if not exists idx_burndown_snapshots_created_by on burndown_snapshots (created_by);
create index if not exists idx_burndown_snapshots_sprint_id on burndown_snapshots (sprint_id);
create index if not exists idx_certification_holders_certification_id on certification_holders (certification_id);
create index if not exists idx_certification_holders_source_course_id on certification_holders (source_course_id);
create index if not exists idx_certification_holders_user_id on certification_holders (user_id);
create index if not exists idx_certification_recerts_decided_by on certification_recerts (decided_by);
create index if not exists idx_certification_recerts_holder_id on certification_recerts (holder_id);
create index if not exists idx_certification_recerts_user_id on certification_recerts (user_id);
create index if not exists idx_change_orders_created_by on change_orders (created_by);
create index if not exists idx_change_orders_project_id on change_orders (project_id);
create index if not exists idx_collab_docs_created_by on collab_docs (created_by);
create index if not exists idx_community_comments_author_id on community_comments (author_id);
create index if not exists idx_community_comments_post_id on community_comments (post_id);
create index if not exists idx_community_posts_author_id on community_posts (author_id);
create index if not exists idx_community_reactions_user_id on community_reactions (user_id);
create index if not exists idx_compliance_findings_created_by on compliance_findings (created_by);
create index if not exists idx_compliance_findings_rule_id on compliance_findings (rule_id);
create index if not exists idx_compliance_findings_run_id on compliance_findings (run_id);
create index if not exists idx_compliance_rules_created_by on compliance_rules (created_by);
create index if not exists idx_compliance_runs_created_by on compliance_runs (created_by);
create index if not exists idx_corpus_sources_triggered_by on corpus_sources (triggered_by);
create index if not exists idx_course_enrollments_course_id on course_enrollments (course_id);
create index if not exists idx_course_enrollments_user_id on course_enrollments (user_id);
create index if not exists idx_course_modules_course_id on course_modules (course_id);
create index if not exists idx_credit_ledger_user_id on credit_ledger (user_id);
create index if not exists idx_credit_orders_credit_product_id on credit_orders (credit_product_id);
create index if not exists idx_credit_orders_user_id on credit_orders (user_id);
create index if not exists idx_discount_codes_created_by on discount_codes (created_by);
create index if not exists idx_emergency_response_plans_created_by on emergency_response_plans (created_by);
create index if not exists idx_emergency_response_plans_project_id on emergency_response_plans (project_id);
create index if not exists idx_event_listings_created_by on event_listings (created_by);
create index if not exists idx_event_listings_event_id on event_listings (event_id);
create index if not exists idx_event_ticket_types_org_id on event_ticket_types (org_id);
create index if not exists idx_function_bookings_client_id on function_bookings (client_id);
create index if not exists idx_function_bookings_created_by on function_bookings (created_by);
create index if not exists idx_function_bookings_project_id on function_bookings (project_id);
create index if not exists idx_function_bookings_space_id on function_bookings (space_id);
create index if not exists idx_function_spaces_created_by on function_spaces (created_by);
create index if not exists idx_goals_created_by on goals (created_by);
create index if not exists idx_goals_owner_id on goals (owner_id);
create index if not exists idx_guest_list_entries_checked_in_by on guest_list_entries (checked_in_by);
create index if not exists idx_guest_list_entries_guest_list_id on guest_list_entries (guest_list_id);
create index if not exists idx_guest_lists_created_by on guest_lists (created_by);
create index if not exists idx_guest_lists_event_id on guest_lists (event_id);
create index if not exists idx_handover_attachments_org_id on handover_attachments (org_id);
create index if not exists idx_handovers_from_user_id on handovers (from_user_id);
create index if not exists idx_handovers_project_id on handovers (project_id);
create index if not exists idx_handovers_to_user_id on handovers (to_user_id);
create index if not exists idx_key_results_created_by on key_results (created_by);
create index if not exists idx_key_results_goal_id on key_results (goal_id);
create index if not exists idx_legend_certifications_created_by on legend_certifications (created_by);
create index if not exists idx_legend_course_reviews_course_id on legend_course_reviews (course_id);
create index if not exists idx_legend_course_reviews_user_id on legend_course_reviews (user_id);
create index if not exists idx_legend_courses_created_by on legend_courses (created_by);
create index if not exists idx_legend_courses_grants_certification_id on legend_courses (grants_certification_id);
create index if not exists idx_legend_crew_members_user_id on legend_crew_members (user_id);
create index if not exists idx_legend_crews_created_by on legend_crews (created_by);
create index if not exists idx_legend_live_sessions_course_id on legend_live_sessions (course_id);
create index if not exists idx_legend_live_sessions_created_by on legend_live_sessions (created_by);
create index if not exists idx_legend_live_sessions_host_id on legend_live_sessions (host_id);
create index if not exists idx_legend_session_registrations_user_id on legend_session_registrations (user_id);
create index if not exists idx_lesson_progress_lesson_id on lesson_progress (lesson_id);
create index if not exists idx_lesson_progress_user_id on lesson_progress (user_id);
create index if not exists idx_lessons_course_id on lessons (course_id);
create index if not exists idx_lessons_module_id on lessons (module_id);
create index if not exists idx_marketplace_listing_photos_org_id on marketplace_listing_photos (org_id);
create index if not exists idx_marketplace_listings_seller_user_id on marketplace_listings (seller_user_id);
create index if not exists idx_meeting_notes_created_by on meeting_notes (created_by);
create index if not exists idx_notes_created_by on notes (created_by);
create index if not exists idx_onsite_order_project_id on onsite_order (project_id);
create index if not exists idx_onsite_points_project_id on onsite_points (project_id);
create index if not exists idx_points_ledger_user_id on points_ledger (user_id);
create index if not exists idx_post_author_id on post (author_id);
create index if not exists idx_presence_venue_zone_id on presence (venue_zone_id);
create index if not exists idx_promoter_attributions_created_by on promoter_attributions (created_by);
create index if not exists idx_promoter_attributions_discount_code_id on promoter_attributions (discount_code_id);
create index if not exists idx_promoter_attributions_promoter_id on promoter_attributions (promoter_id);
create index if not exists idx_promoters_created_by on promoters (created_by);
create index if not exists idx_rams_assessments_created_by on rams_assessments (created_by);
create index if not exists idx_rams_assessments_project_id on rams_assessments (project_id);
create index if not exists idx_reservations_created_by on reservations (created_by);
create index if not exists idx_resource_collections_created_by on resource_collections (created_by);
create index if not exists idx_resources_collection_id on resources (collection_id);
create index if not exists idx_resources_created_by on resources (created_by);
create index if not exists idx_revenue_orders_event_listing_id on revenue_orders (event_listing_id);
create index if not exists idx_run_of_shows_created_by on run_of_shows (created_by);
create index if not exists idx_run_of_shows_event_id on run_of_shows (event_id);
create index if not exists idx_run_of_shows_project_id on run_of_shows (project_id);
create index if not exists idx_scene_created_by on scene (created_by);
create index if not exists idx_sheet_rows_created_by on sheet_rows (created_by);
create index if not exists idx_sheet_rows_sheet_id on sheet_rows (sheet_id);
create index if not exists idx_sheets_created_by on sheets (created_by);
create index if not exists idx_shift_notes_author_id on shift_notes (author_id);
create index if not exists idx_shift_notes_time_entry_id on shift_notes (time_entry_id);
create index if not exists idx_show_recaps_created_by on show_recaps (created_by);
create index if not exists idx_show_recaps_event_id on show_recaps (event_id);
create index if not exists idx_show_recaps_project_id on show_recaps (project_id);
create index if not exists idx_signage_placements_created_by on signage_placements (created_by);
create index if not exists idx_signage_placements_project_id on signage_placements (project_id);
create index if not exists idx_signage_placements_sign_id on signage_placements (sign_id);
create index if not exists idx_signage_signs_created_by on signage_signs (created_by);
create index if not exists idx_sops_created_by on sops (created_by);
create index if not exists idx_sprint_stories_created_by on sprint_stories (created_by);
create index if not exists idx_sprint_stories_sprint_id on sprint_stories (sprint_id);
create index if not exists idx_sprints_created_by on sprints (created_by);
create index if not exists idx_sprints_project_id on sprints (project_id);
create index if not exists idx_store_cart_items_org_id on store_cart_items (org_id);
create index if not exists idx_store_cart_items_product_id on store_cart_items (product_id);
create index if not exists idx_store_cart_items_variant_id on store_cart_items (variant_id);
create index if not exists idx_store_product_variants_product_id on store_product_variants (product_id);
create index if not exists idx_store_products_created_by on store_products (created_by);
create index if not exists idx_task_attachments_task_id on task_attachments (task_id);
create index if not exists idx_task_attachments_uploaded_by on task_attachments (uploaded_by);
create index if not exists idx_task_comments_author_id on task_comments (author_id);
create index if not exists idx_task_comments_task_id on task_comments (task_id);
create index if not exists idx_task_events_actor_id on task_events (actor_id);
create index if not exists idx_task_events_task_id on task_events (task_id);
create index if not exists idx_vendor_onboarding_items_vendor_id on vendor_onboarding_items (vendor_id);
create index if not exists idx_venue_tables_created_by on venue_tables (created_by);
create index if not exists idx_video_call_participants_call_id on video_call_participants (call_id);
create index if not exists idx_video_call_participants_user_id on video_call_participants (user_id);
create index if not exists idx_video_calls_created_by on video_calls (created_by);
create index if not exists idx_video_calls_meeting_id on video_calls (meeting_id);
create index if not exists idx_voucher_redemptions_user_id on voucher_redemptions (user_id);
create index if not exists idx_vouchers_created_by on vouchers (created_by);
create index if not exists idx_whiteboards_created_by on whiteboards (created_by);
create index if not exists idx_whiteboards_updated_by on whiteboards (updated_by);
create index if not exists idx_xpms_catalog_staging_best_atom_id on xpms_catalog_staging (best_atom_id);

-- Drop redundant duplicate indexes (constraint/identical twin kept):
drop index if exists public.ai_agents_target_idx;
drop index if exists public.idx_budgets_project_id;
drop index if exists public.burndown_snapshots_sprint_idx;
drop index if exists public.config_values_lookup;
drop index if exists public.ic_msas_public_token_idx;
drop index if exists public.job_applications_posting_status_idx;
drop index if exists public.job_postings_status_published_idx;
drop index if exists public.offer_letters_token_idx;
drop index if exists public.open_call_submissions_status_idx;
drop index if exists public.open_calls_status_published_idx;
drop index if exists public.proposal_share_links_token_idx;
drop index if exists public.talent_offers_status_idx;
