-- Tighten storage RLS to gate uploads AND reads on org-folder
-- membership. The earlier 0031 version was authored but never applied
-- (modifying policies on storage.objects requires the `supabase_admin`
-- role which neither the MCP key nor `supabase migrate` posseses).
-- This is the canonical replacement.
--
-- ⚠️ APPLY VIA DASHBOARD → SQL EDITOR (logged in as the project's
-- superuser owner). MCP attempts return:
--     ERROR:  42501: must be owner of relation objects
--
-- The statements below are wrapped in a DO block with an
-- `insufficient_privilege` catcher so:
--   - local Docker `supabase db reset` no-ops the block (dev role
--     can't touch storage.objects)
--   - the migration apply tracker marks 0045 as run on the remote
--     (when an operator runs `supabase migrate` for the first time
--     post-rename) without bricking the chain
--
-- The Dashboard apply is still the only way to make the policies
-- actually live on the remote. See docs/runbooks/seaworthy-ops.md.

DO $sa$ BEGIN
  drop policy if exists storage_authenticated_upload on storage.objects;
  drop policy if exists storage_org_scoped_upload on storage.objects;
  drop policy if exists storage_service_role_buckets_upload on storage.objects;
  drop policy if exists storage_signed_read on storage.objects;
  drop policy if exists storage_org_scoped_read on storage.objects;

  -- Service-role-only buckets — server jobs (PDF generators) write
  -- here via service_role; the authenticated INSERT policy is kept
  -- permissive within those buckets so a future server-action that
  -- writes via the session client doesn't 403 mysteriously.
  create policy storage_service_role_buckets_upload on storage.objects
    for insert to authenticated
    with check (
      bucket_id = any (array[
        'proposals'::text,
        'receipts'::text,
        'credentials'::text,
        'branding'::text,
        'procore-parity'::text
      ])
    );

  -- User-direct upload buckets: path[1] must be a member-org.
  create policy storage_org_scoped_upload on storage.objects
    for insert to authenticated
    with check (
      bucket_id = any (array['advancing'::text, 'incident-photos'::text])
      and exists (
        select 1
        from public.memberships m
        where m.user_id = (select auth.uid())
          and m.org_id::text = (storage.foldername(name))[1]
          and m.deleted_at is null
      )
    );

  -- READ: same org-folder gate. Replaces the wide-open
  -- `storage_signed_read` policy. Signed URLs (which bypass RLS) still
  -- work for legitimate share-link flows.
  create policy storage_org_scoped_read on storage.objects
    for select to authenticated
    using (
      bucket_id = any (array[
        'advancing'::text,
        'receipts'::text,
        'proposals'::text,
        'credentials'::text,
        'branding'::text,
        'incident-photos'::text,
        'procore-parity'::text
      ])
      and exists (
        select 1
        from public.memberships m
        where m.user_id = (select auth.uid())
          and m.org_id::text = (storage.foldername(name))[1]
          and m.deleted_at is null
      )
    );

  comment on policy storage_service_role_buckets_upload on storage.objects is
    'Permissive insert for service-role-only buckets (PDF generators write via compileAndStore in src/lib/pdf/render.ts).';

  comment on policy storage_org_scoped_upload on storage.objects is
    'Org-folder enforcement for user-direct upload buckets. Path[1] must be one of the user''s ACTIVE org_ids (deleted_at IS NULL).';

  comment on policy storage_org_scoped_read on storage.objects is
    'Org-folder enforcement for direct authenticated reads. Path[1] must be one of the user''s ACTIVE org_ids. Signed-URL reads (generated by service_role) bypass RLS and remain functional.';
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Skipping storage.objects policies — current role lacks supabase_admin. Apply via Dashboard SQL Editor (see 0045 header).';
END $sa$;
